### ISSUE TITLE
static library logging

### ISSUE THREAD

**Issue by rhd** [SergiusTheBest/plog#10]
Hi,

I've seen your static library example. Is it possible to turn off logging from a library of I'm not interested in seeing its output?

For example: If the library does `LOGD << "debug message"` a lot and I have a bunch of `LOGD << "some other messages"` in my main app - is it possible to quite down the logging from the library? Or is it all or nothing?

Thanks!

**Comment by SergiusTheBest** [comment]
Hi!

Yes, it's possible but the library and your app should write to the different loggers. Take a look at the [Facilities](https://github.com/SergiusTheBest/plog/blob/master/samples/Facilities/Main.cpp) sample.

Cheers!

**Comment by rhd** [comment]
Hi,

So, is the -1 for the instance number significant? Or could the sink logger really be anything? Should the sink logger always be set to `plog::verbose` to make sure everything that gets sent to the logger gets logged?

**Comment by SergiusTheBest** [comment]
The logger instance numbers are arbitrary and can be anything you want. 

Think about the sink logger severity level as a global filter. I recommend to leave it at `plog::verbose` and control the first level loggers (thus lazy evaluation can work).

**Comment by rhd** [comment]
makes perfect sense - thanks.

Can you take a look at my pull request and tell me what you think about being able to change the default instance number?

I'm using the patch now and it seems to work well.

I'm closing this issue.
