### ISSUE TITLE
I want to rotate when starting process each time

### ISSUE THREAD

**Issue by tillmanchen2015** [SergiusTheBest/plog#100]
Now plog will append new logs to last log files each time when I start my process. Is there a way to let plog to create a new log file?

**Comment by SergiusTheBest** [comment]
Right now there is no such option. You can replace `openLogFile` with `rollLogFiles` at https://github.com/SergiusTheBest/plog/blob/master/include/plog/Appenders/RollingFileAppender.h#L39 to get the desired behavior.

**Comment by tillmanchen2015** [comment]
Thanks

**Comment by SergiusTheBest** [comment]
After merging #103 you can just call `rollLogFiles` at the startup.

**Comment by tillmanchen2015** [comment]
hi SergiusTheBest,
I used plog following your comment to replace openLogFile with rollLogFiles. Sometimes the log didn't work after running some time. It seemed the error occurred at the point to rotate. Can you analyse if it was related to my individual changing?

**Comment by SergiusTheBest** [comment]
Hi @tillmanchen2015,

Is there a free space on disk? The code is fine. Can you post your changes?

**Comment by tillmanchen2015** [comment]
@SergiusTheBest ,
I think issue occurred in log init:
plog::init<plog::SimpleFormatter>(get_log_level(config_file->log_level), p.string().c_str(), 5000000, 1000);

After one log file is finished, it cannot generate new log file. But this case only occurred in product environment, which is a windows server. I cannot reproduce it in test server. Then I changed 1000 to 100 and 5000000 to 4000000. Now it works again.

**Comment by SergiusTheBest** [comment]
@tillmanchen2015 ,
Oh, 1000 files takes a lot of time to rotate.
