### ISSUE TITLE
Log in UTC datetime

### ISSUE THREAD

**Issue by hcognet** [SergiusTheBest/plog#101]
Hi,
Is there a possibility to choose the date timezone of the logs in order to write the time in UTC for example?
Thank you for your feedback.

**Comment by SergiusTheBest** [comment]
Hi! 
Do you want to write time in UTC+0?

**Comment by hcognet** [comment]
Hi!
Yes, I would like that. (having a single time reference is easier)

**Comment by SergiusTheBest** [comment]
Oh, I see. I think we can use a global compile-time switch to turn this feature on/off. Will it work for you?

**Comment by hcognet** [comment]
Yes, it should fit me perfectly.

**Comment by SergiusTheBest** [comment]
Ok.

**Comment by SergiusTheBest** [comment]
I've added `TxtFormatterUtcTime` and `CsvFormatterUtcTime` to get time in UTC. Please try them.
