### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by effolkronium** [SergiusTheBest/plog#106]

**Comment by effolkronium** [comment]
CMake also useful for Header-only libraries

https://youtu.be/bsXLMQ6WgIk?list=PLipOu-dBGhQE_JA4Fs8olRbDiu3MxaGch&t=1689

**Comment by SergiusTheBest** [comment]
Yes, moving to modern CMake is in progress.

**Comment by SergiusTheBest** [comment]
Done.
