### ISSUE TITLE
Don't see any log output at all

### ISSUE THREAD

**Issue by jbmonroe** [SergiusTheBest/plog#110]
Like the now-closed #49, I'm doing a fairly simple set-up, and I can see my application working, but there's no logging.

This seems like it's correct:

`plog::init(plog::verbose, cfg.logFile, 512 * 1024, 4);`

and the actual logging

`LOG_INFO << "email sent";`

appears correct, and when I follow it in the debugger, it seems to do what's required.

But after multiple runs and tests, there's still no log.  It didn't append to the legacy log file already on the drive, and deleting that didn't cause it to generate a new log file.  

Building in VS2013.

What am I doing wrong?

**Comment by SergiusTheBest** [comment]
Everything is correct. The file path `myLog.log` is a relative file path and the log file will be created in the working directory (usually a directory of your executable but can be anything as it depends on how your app is launched).

**Comment by jbmonroe** [comment]
Except that simply listing "myLog.log" as the file doesn't produce a log file.  Even "./mylog.log" doesn't produce a file.

**Comment by SergiusTheBest** [comment]
What is the working directory?  If it is `program files` your app may not have rights to create files there. Please check.

**Comment by jbmonroe** [comment]
C:\dev\argus\argus, which VS2013 uses as the working folder during debugging.

**Comment by SergiusTheBest** [comment]
Could you start your app from the console? Just to make sure that it is not some settings in Visual Studio affect the log.

**Comment by jbmonroe** [comment]
I just ran the release version from the console and got a log when I did a full path, but nothing if I just named a file in the configuration.  So that leaves the score at

argus.log             | 0
c:\logs\argus.log | 1

I walked down into the code during a debug run and saw that when the library opened the argus.log file it seemed to think the file already contained 10K, so that means the file is being written someplace I haven't looked for it--and it's not in the working directory for the project.  That search is underway.

**Comment by SergiusTheBest** [comment]
Did you figure out the log location? You can get your current work directory path with the following code:

```cpp
char buffer[MAX_PATH] = {};
getcwd(buffer, MAX_PATH);

std::cout << buffer << std::endl;
```

**Comment by jbmonroe** [comment]
I wasn't able to figure out where it was putting the log--but it's no big
deal to just provide a full path to the log file.

**Comment by SergiusTheBest** [comment]
Ok.
