### ISSUE TITLE
Static analysis error "Cannot resolve symbol 'ref'"

### ISSUE THREAD

**Issue by SergiusTheBest** [SergiusTheBest/plog#116]
I have a similiar problem. Happens when using Visual Studio 2017. On mouse hover error message is "Cannot resolve symbol 'ref'.
In error list: class "plog::Record" has no member "ref"

Happens when using any log macro, for example 
`LOG_DEBUG << "anything";`
It is only static analysis error. Compiles and works OK. 
Macro expands to:
`if (!plog::get<0>() || !plog::get<0>()->checkSeverity(plog::debug)) {;} else (*plog::get<0>()) += plog::Record(plog::debug, __FUNCTION__, 25, "", __if_exists(this) { this } __if_not_exists(this) { 0 }).ref() << "anything";`

_Originally posted by @domenn in https://github.com/SergiusTheBest/plog/issues/114#issuecomment-450564980_

**Comment by SergiusTheBest** [comment]
@domenn Is it possible that you have 2 plog versions at the same time in include path?

**Comment by domenn** [comment]
No. I use project as git submodule and add include path with cmake.
I forgot to mention one detail: I am using Resharper c++. 

I am checking the code of the library, makes no sense why VS would complain. Maybe VS bug.

**Comment by SergiusTheBest** [comment]
I'll recheck it with VS2017 but I don't remember any issues with it.

**Comment by domenn** [comment]
I tried on other computer today with clean visual studio. Without Resharper. It works, no error.
I will try to find out if Resharper causes the problem, currently have problems with it. Will keep you informed, for now we can assume this issue as not existing.

**Comment by domenn** [comment]
Resharper has problems with __if_exists. Maybe issue should be raised to JetBrains. By commenting out the code as suggested in other issue: 
```//#if defined(_MSC_VER) && _MSC_VER >= 1600 && !defined(__INTELLISENSE__) && !defined(__INTEL_COMPILER) && !defined(__llvm__) // >= Visual Studio 2010, skip IntelliSense, Intel Compiler and Clang Code Model
//#   define PLOG_GET_THIS()      __if_exists(this) { this } __if_not_exists(this) { 0 }
//#else
#   define PLOG_GET_THIS()      reinterpret_cast<void*>(0)
//#endif```

The error dissapears. Somehow I missed this detail yesterday.
Problem is with if_exists. That's how it looks on my side (just realized that I can add screenshots to github):
![image](https://user-images.githubusercontent.com/30743731/50567945-66357b00-0d4b-11e9-9e18-d07c694fd7a1.png)

I now know workaround that works for me, so I will stop researching this.

**Comment by SergiusTheBest** [comment]
Could you check this 81b9f1f092ca546f0ad4d94c4b415ffeb5409172 ? I don't have ReSharper right now but according to their [documentation](https://www.jetbrains.com/help/resharper/ReSharper_by_Language_CPP.html) the fix should work.

**Comment by domenn** [comment]
It removes the error, so works for me. 
Thanks for the effort!

**Comment by SergiusTheBest** [comment]
Perfect! Thank you too!
