### ISSUE TITLE
Logging to stderr

### ISSUE THREAD

**Issue by pesho-ivanov** [SergiusTheBest/plog#117]
Hey! My program uses stdout for its own output. What is the recommended way redirect the plog output to stderr? Thanks

**Comment by SergiusTheBest** [comment]
Output stream is not configurable. You need to copy `ConsoleAppender.h` to `ConsoleAppenderStderr.h` and change `stdout` to `stderr` in code (also change class name).

**Comment by pesho-ivanov** [comment]
Thank you for the quick reply. I guess this thread can be relabeled to "enhancement" then.

**Comment by SergiusTheBest** [comment]
I mark "question" issues with no code. BTW did you manage to accomplish your goal?

**Comment by pesho-ivanov** [comment]
As you said, changing `stdout` to `stderr` and `cout` to `cerr` did the job. Meanwhile, I started wondering why isn't `stderr` the default output stream.

**Comment by ababo** [comment]
I really don't get why you support `stdout` instead of `stderr`.

**Comment by SergiusTheBest** [comment]
@ababo Well, there is no generally accepted convention there. I can see that all possible scenarios are used across different products:
* write logs to `stdout`
* write logs to `stderr`
* write info logs to `stdout` and error logs to `stderr`

So it should be configurable. I'll think how to implement it.

**Comment by ababo** [comment]
https://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout

**Comment by SergiusTheBest** [comment]
Adding more discussions (just for reference):
* https://github.com/sorintlab/stolon/issues/375
* https://github.com/ipfs/go-log/issues/60
* https://github.com/symfony/symfony/issues/29941
* https://github.com/envoyproxy/envoy/issues/8620
* https://github.com/nim-lang/Nim/issues/9547
* https://github.com/fluxcd/flux/issues/1491

**Comment by SergiusTheBest** [comment]
The fix is in the `master`. Now you can choose where to log to: stderr or stdout.
