### ISSUE TITLE
C++11/Clang warning

### ISSUE THREAD

**Issue by cyberstealth1024** [SergiusTheBest/plog#124]
I get a warning whenever invoking `LOGI << "stuff";` and similar in Qt Creator with ClangCodeModel (and Qt 5.11.1, MinGW 5.3.0).  Specifically:

"zero as null pointer constant"...
"expanded from macro 'LOGI'"...
"expanded from macro 'LOG_INFO'"...
"expanded from macro 'LOG'" ...
"expanded from macro 'LOG_'" ...
"expanded from macro 'PLOG_GET_THIS'"

(pheew, that's a lot of macro expansion!)

I resolved this by changing Log.h from
`#define PLOG_GET_THIS()     0`
to 
`#define PLOG_GET_THIS()     nullptr`

I'm sure there are other areas where this needs to be done (and for other compilers, etc), but this solved my immediate problem.

Change request:  add in conditional preprocessor directives to test for C++11 and above and use nullptr for this and other areas.

That being said, good work on plog!

**Comment by cyberstealth1024** [comment]
Never mind.  It seems like this was resolved a few months ago in commit b56969ec12dacc40b08daa211e336feead538e94

via
`#   define PLOG_GET_THIS()      reinterpret_cast<void*>(0)`

**Comment by SergiusTheBest** [comment]
Ok, I'm closing the issue if it is resolved already.
