### ISSUE TITLE
No way to turn off building samples

### ISSUE THREAD

**Issue by kohnech** [SergiusTheBest/plog#125]
Samples are always build even as a ExternalProject_Add.
In order to disable building samples add this option to your configure:
-DBUILD_SAMPLES=OFF

**Comment by SergiusTheBest** [comment]
Hi @kohnech ,

Personally I'm using git submodules and `add_subdirectory` in CMakeLists to add 3rd-party components. However `ExternalProject_Add` is a good alternative approach. Could you post your sample CMakeLists with `ExternalProject_Add` to see how do you use it?

**Comment by kohnech** [comment]
Hi @SergiusTheBest 
I see. Is your project structure like this:
```Bash
my_project
   |
   +- CMakeLists.txt    ;root CMake file
   |    |
   |    +- src
   |    +- include     
   |    +- <other common>
   |
   +- git_submodule
        |
        +- CMakeLists.txt
```
Here follows example from my external dependencies:
```Bash
cmake_minimum_required(VERSION 3.0)
project(3rd-party)
set(PLOG_VERSION 1.1.4)

include(GNUInstallDirs)
include(ExternalProject)

############# plog

ExternalProject_Add(
    plog
    URL ${CMAKE_CURRENT_SOURCE_DIR}/plog-${PLOG_VERSION}.tar.gz
    INSTALL_DIR ${CMAKE_CURRENT_SOURCE_DIR}/plog-${PLOG_VERSION}
    CMAKE_ARGS  -D CMAKE_BUILD_TYPE=Release
                -D CMAKE_INSTALL_PREFIX=<INSTALL_DIR>
                -D BUILD_SAMPLES=OFF

#### Other 3rd-parties ....
```
As you see from the URL I prefer to have the source code in a *.tar.gz so I don't rely on internet (I want to be able to support my project after 10 years).
My project structure is like this
```Bash
my_project
   |
   +- CMakeLists.txt    ;root CMake file
   |    |
   |    +- src
   |    +- include     
   |    +- <other common>
   |
   +- 3rd-party
        |
        +- CMakeLists.txt (see the file listed above)
        +- plog-1.1.4.tar.gz
```

I have an idea that will work with both ways. If you like I can update the PR. It would be to nestle both of these user cases in something like this:

```Bash
option(BUILD_SAMPLES "Building samples" ON)
# check if building as a stand-alone project
if(${CURRENT_SOURCE_DIR} STREQUAL ${SOURCE_DIR})
if(BUILD_SAMPLES)
```

**Comment by kohnech** [comment]
I have updated the PR and tested with both
- [x] Support git submodule add
- [x] Support ExternalProject_Add
as stated in comment above.

**Comment by SergiusTheBest** [comment]
Thank you, I'll check it out. It's interesting approach with tar.gz!
