### ISSUE TITLE
Enhancement request: do not include plog/Init.h in plog/Log.h

### ISSUE THREAD

**Issue by gordhub** [SergiusTheBest/plog#127]
Nice package, easy to make use of!

I have a project that is built from several separate compile units, all of which need to do logging. Before using plog in the real code, I built some test cases to ensure it works. While researching various logging packages, I noticed that it was a common complaint about header-only packages that the size of executables could grow greatly, so I decided to investigate with some small test programs.

My initial test program contained these plog includes:
```
#include <plog/Log.h>
#include <plog/Appenders/ConsoleAppender.h>
```
and produced an executable with:
MODULE SIZE (HEX)   00038B18

Added a second compile unit containing plog include:
```
#include <plog/Log.h>
```
and only these functions:
```
void shout(char * message) {
    LOG_ERROR << message;
}

void say(char * message) {
    LOG_INFO << message;
}

void whisper(char * message) {
    LOG_DEBUG << message;
}
```
The executable containing the objects from both compile units:
MODULE SIZE (HEX)   000595F0

Added a third compile unit containing plog include:
```
#include <plog/Log.h>
```
and only this function:
```
void yell(char * message) {
    LOG_FATAL << message;
}
```
The executable containing the objects from the three compile units:
MODULE SIZE (HEX)   0007C760

So growth of the executable is 130-140 K per small added compile unit.

I followed the advice of the reporter of issue #89, commented `#include <plog/Init.h>` in plog/Log.h, and added `#include <plog/Init.h>` to the main program that initializes plog. Rebuilt all three programs, and the executable size was then:
MODULE SIZE (HEX)   0004F600
Program execution is unchanged.

This is a substantial reduction in executable size, and the only penalty is the need to add `#include <plog/Init.h>` to the compile unit that initializes plog. Please consider making this change. Thanks!

**Comment by SergiusTheBest** [comment]
Hi @gordhub ,

I ran a quick test on msvc and got the same binary size with and without `#include <plog/Init.h` for 4 compile units.

What compiler and flags do you use? I want to be able to reproduce the issue.

**Comment by gordhub** [comment]
Hi @SergiusTheBest, 

Very interesting that your test with msvc showed no size difference.

I am using the Dignus Systems/C++ compiler ( http://dignus.com/products.shtml#syscplusplus )...the compiler isn't free or even nearly so, so I wouldn't expect you to be able to use the compiler.

Here is a sample compile showing flags:
```
dcxx  -D_EDC_ADD_ERRNO2=1 -DOS390 -D__MVS__ -D__EXTENDED__ -D_EXT -D_OPEN_THREADS -D_XOPEN_SOURCE=500 -D_XOPEN_SOURCE_EXTENDED=1 -D_OPEN_SYS -D_OPEN_MSGQ_EXT -D_POSIX_SOURCE -D_LONG_LONG -D__C99__FUNC__  -I/include -I/home/gord/projects/zosv2r2c/usr/include -I/home/gord/projects/zosv2r2c/usr/lpp/ioclib/include -I/home/gord/projects/zosv2r2c/usr/lpp/gskssl/include  -I/home/gord/projects/plog/include -I/home/gord/projects/mzca/src -fc370=z1r11 -fno_showinc -fstructmap -fstructmaphex -fwarn_disable=1 -fwarn_disable=161 -fwarn_disable=1052 -fwarn_disable=1056 -fwarn_disable=191 -fwarn_disable=1205 -fwarn_disable=815 -fwarn_disable=1381 -fwarn_disable=375 -ftrim -famode=31 -flisting=/home/gord/projects/mzca/sandbox/listings/drvplog3-dcxx.txt -o /home/gord/projects/mzca/sandbox/tmp/drvplog3.s drvplog3.cpp
DCXX Dignus Systems/C++ Compiler - version 2.10.12 Nov  8 2018 18:55:42
   (c) Copyright 1999-2018  Dignus, LLC   All rights reserved.
DCXX is licensed to Action Software (1-User Linux).
DCXX Return code 0, elapsed time 0.43 seconds.
dasm -macext . -L/home/gord/projects/mz/prod/mac -L/home/gord/projects/zosv2r2c/cee/sceemac -L/home/gord/projects/zosv2r2c/sys1/maclib -L/home/gord/projects/zosv2r2c/sys1/modgen -L/usr/local/dignus/2_10/maclib -fmaxrc=0 -fdupalias -flisting=/home/gord/projects/mzca/sandbox/listings/drvplog3-dasm.txt -o drvplog3.o /home/gord/projects/mzca/sandbox/tmp/drvplog3.s
DASM Dignus Systems/ASM - version 1.95.00
  (c) Copyright Dignus, LLC  1994-2016  All rights reserved.
DASM is licensed to Action Software (1-User Linux).
DASM Return code 0, elapsed time 0.09 seconds, object code size X'C96F'.
cp drvplog3.o /home/gord/projects/mzca/sandbox/obj/drvplog3
```
I am presently compiling with `#include <plog/Init.h>` commented in plog/Log.h. The program drvplog3 compiled above is not the program that calls plog::init(). It just has the yell() function shown in my previous message. The resulting object size is X'C96F'. If I add `#include <plog/Init.h>` after `#include <plog/Log.h>` in this program (effectively undoing the effect of commenting `#include <plog/Init.h>` commented in plog/Log.h), then the object size for drvplog3 increases to X'2288F'. When I look at the Assembler source emitted by the compiler, I see that code has been generated for init(), even though it is defined as inline in the header and is never called in this program. The compiler may be choosing not to honor the inline specification. 

For my own purposes, I'm OK with commenting `#include <plog/Init.h>` in plog/Log.h; I thought it might be useful to others to minimize the size of the executables they build. Given your results, my results, and the results for the OP of issue #89, clearly it's dependent on the compiler in use whether the problem exists.
