### ISSUE TITLE
fatal error C1189: #error:  WinSock.h has already been included

### ISSUE THREAD

**Issue by sstsai** [SergiusTheBest/plog#13]
using logger with another library that includes winsock.h generates this error.
adding:
#define WIN32_LEAN_AND_MEAN
before:
#include <Windows.h>
in:
Util.h fixed this for me.

**Comment by SergiusTheBest** [comment]
Thanks for reporting! I'll check it.

**Comment by SergiusTheBest** [comment]
I've researched this issue: WIN32_LEAN_AND_MEAN helps in your case but in others it can do harm. So the solution is to make an application developer responsible for defining WIN32_LEAN_AND_MEAN. He knows better whether he needs it and where and how to define it (for example it can be defined globally in project properties or in a precompiled header).
