### ISSUE TITLE
how to disble all logs in Release build?

### ISSUE THREAD

**Issue by quanzhuo** [SergiusTheBest/plog#130]
how to disble all logs in Release build?
Is there an macro or something else ?

Thanks you

**Comment by snOm3ad** [comment]
Change the severity of the log to 'none', this will avoid printing anything that has a higher severity which is basically all of the other options.

**Comment by SergiusTheBest** [comment]
@snOm3ad is right, you can change the logger severity to `none` or even skip logger initialization:
```cpp
#ifndef _DEBUG
    plog::init(plog::debug, "Demo.csv", 5000, 3); // Initialize the logger.
#endif
```
But the logging code will remain in your binary. Is this a problem for your case?

**Comment by quanzhuo** [comment]
> @snOm3ad is right, you can change the logger severity to `none` or even skip logger initialization:
> 
> ```c++
> #ifndef _DEBUG
>     plog::init(plog::debug, "Demo.csv", 5000, 3); // Initialize the logger.
> #endif
> ```
> 
> But the logging code will remain in your binary. Is this a problem for your case?

Yes

**Comment by SergiusTheBest** [comment]
@quanzhuo  I see. I can introduce a macro for that.

**Comment by KarateSnowMachine** [comment]
I have not tested this, but if we set the severity to `plog::none`, does the code that builds the strings still execute? For example if I have some very complex expression like `LOG_VERBOSE << foo->bar() << foo->baz() << "1234" << some_really_long_computation();` (obviously this is a contrived example but I'm trying to understand whether it's ok to leave logging statements in hot paths that are not typically going to be used).

**Comment by SergiusTheBest** [comment]
@KarateSnowMachine No, that code will not be executed. See [lazy-stream-evaluation](https://github.com/SergiusTheBest/plog#lazy-stream-evaluation).

**Comment by codemedic** [comment]
@SergiusTheBest That is a fab feature. Can you explain how it works under the hood please.

**Comment by SergiusTheBest** [comment]
@codemedic It works like `if` statement:
```cpp
if (requeredLogLevel)
{
    stream << foo->bar() << foo->baz() << "1234";
}
```
but hidden behind a macro and a ternary operator.

**Comment by mackncheesiest** [comment]
Just curious, did a macro ever get introduced for this? 

If not, is the best solution to simply set the log level to `none` and wrap `plog::init` inside an `#ifndef BUILD_OPTIMIZED` block? 
And would there be any appreciable difference compared to wrapping, for instance, all logging statements in that same `#ifndef BUILD_OPTIMIZED` flag?

**Comment by SergiusTheBest** [comment]
@mackncheesiest Define `PLOG_DISABLE_LOGGING` to disable logging and reduce binary size. Take a look at [DisableLogging](samples/DisableLogging/Main.cpp) sample for more info.

**Comment by mackncheesiest** [comment]
Thanks @SergiusTheBest -- you're the best!
