### ISSUE TITLE
Disable PLOG_GET_THIS() as ms extension doesn't work in all cases

### ISSUE THREAD

**Issue by SergiusTheBest** [SergiusTheBest/plog#132]
The following code produces `error C3493: 'this' cannot be implicitly captured because no default capture mode has been specified`:
```cpp
void MyClass::method()
{
    []() { PLOGD; };
}
```

**Comment by extmchristensen** [comment]
Yes, also got this problem a couple of times.

**Comment by SMelanko** [comment]
I have got this issue. What can we do now as a workaround solution? Is it ok just add `this` in capture list?

![image](https://user-images.githubusercontent.com/7338369/63356359-50270a00-c370-11e9-8395-d1f8ba317693.png)

**Comment by SergiusTheBest** [comment]
I pushed the changes. Please check them.
