### ISSUE TITLE
File Path Problem

### ISSUE THREAD

**Issue by wanjudadao** [SergiusTheBest/plog#138]
I tried to follow your setup step, but for the beginning step, like to #include "Plog/plog.h" does not work for me. As my Compiler said the 'Plog' is an undeclared identifier. So can you tell me what I can do for that? My system is Ubuntu 16.04, I put the Plog to a self-defined folder. Thank you so much!

**Comment by SergiusTheBest** [comment]
How to add path to include directories depends on what build system do you use: makefile, cmake, qt-project and so on. I recommend to use cmake.

**Comment by SergiusTheBest** [comment]
@wanjudadao How is it going?

**Comment by SergiusTheBest** [comment]
I hope @wanjudadao found an answer so I'm closing this issue.
