### ISSUE TITLE
Can we support the printf style without dependency on fmtlib?

### ISSUE THREAD

**Issue by kakyoism** [SergiusTheBest/plog#139]
Right now with current `fmtlib`, `fmt::sprintf` is no longer there, causing a build failure in my app. I'm sure there must be a reason, but the dependency on fmtlib is just a letdown. 

Right now plog is the only functional logger that I checked. Great job. `loguru` and `spdlog` supports the printf formatting out of the box, but they have other issues on Windows such as wchar support and unsafe API compiler errors. 

If plog could introduce the formatting natively it'd be perfect!

**Comment by SergiusTheBest** [comment]
Yes, it can be done.

**Comment by SergiusTheBest** [comment]
Ok, I've added `printf` method, so now fmtlib is not required:
```cpp
PLOGI.printf("%d %s", 42, "test");
```

**Comment by SergiusTheBest** [comment]
@kakyoism Please, test it. Use the latest master.
