### ISSUE TITLE
How to write to stdout

### ISSUE THREAD

**Issue by vervenumen** [SergiusTheBest/plog#14]
Hi!
Every time I use the "LOG_VERBOSE<<1;" it seems to write it to a new line.
Also, in "LOG_VERBOSE<<1<<2;" timestamp and other info are printed twice.
Is there a functionality with which I can control when the newlines are inserted?
In other words, I need something very close to standard 'cout', but with timestamp inserted just once in a line...

**Comment by SergiusTheBest** [comment]
Hi @vervenumen ,

The code:
```cpp
static plog::ColorConsoleAppender<plog::TxtFormatter> consoleAppender;
plog::init(plog::verbose, &consoleAppender);

LOG_VERBOSE << 1 << 2;
```

outputs:
```
2015-11-17 13:02:55.020 VERB  [38304] [main@14] 12
```

It inserts new line in the end and not after each token. 

Can you paste your code here?

**Comment by SergiusTheBest** [comment]
Are there any news?

**Comment by vervenumen** [comment]
Its working for me now! Oddly enough, I am unable to recreate the original problem.
Anyways, thanks for helping out!!

**Comment by SergiusTheBest** [comment]
Ok, closing the issue.
