### ISSUE TITLE
Log flushed to disk only at end of program

### ISSUE THREAD

**Issue by jseparovic** [SergiusTheBest/plog#140]
I'm using Windows 10 x64 and Ubuntu "tail -f" to follow the log.
Consider the following example:
```
    plog::init(plog::debug, logfile);
    PLOGD << "Hello log!";
    Sleep(10000);
```

I noticed that using Ubuntu tail, messages are not shown straight away, but after the 10 second call to Sleep.
However, if I use BareTail as well, the log messages are printed right away (to both BareTail and Ubuntu tail)

Am I able to get the instant flush behavior just when using Ubuntu for Windows, tail -f ?

**Comment by SergiusTheBest** [comment]
Messages are sent to the file right away. Plog uses low-level file API, so there is no caching in C runtime.
Are you running WSL? If yes take a look at https://github.com/Microsoft/WSL/issues/3292. Probably it's your case.

**Comment by jseparovic** [comment]
Perfect! Thanks mate
