### ISSUE TITLE
How to use one log file with different formatters based on multiple instance 

### ISSUE THREAD

**Issue by htome** [SergiusTheBest/plog#141]
Hi  there,

How can I use the same log file but with a different formatter based on a instance?

I can use a Custom Formatter, but the Record passed to
`static util::nstring format(const Record& record)`
does not have info about the instance of the logger being used.

What is the best way to achieve this?

Thanks!

**Comment by SergiusTheBest** [comment]
Hi @htome!

It's not possible to do what you want without a modification of plog. The idea is to keep file formatting consistent, so it can be easily parsed.  Consider having 2 separate log files.

But if need only 1 file then yes, you can add instance information to `Record` and use it in you custom formatter.

**Comment by htome** [comment]
Hi Sergius,
You are right. I didn't think about the implications of parsing.
Is there a way to customize "Record" without changing the Original plog?
If not, every time there is a update I will need to re-introduce the change.
Please let me know

**Comment by SergiusTheBest** [comment]
I'll add instance number to `Record`. Could be useful in some scenarios.

**Comment by SergiusTheBest** [comment]
Done.
