### ISSUE TITLE
define PLOG_CAPTURE_FILE can't enable __FILE__.

### ISSUE THREAD

**Issue by Django-xinfa** [SergiusTheBest/plog#142]
I compile Hello example by g++ -Wall -std=c++11 -W -D PLOG_CAPTURE_FILE -c Main.cpp -o Main.o -I./ -I../../include/. There is no filename string in Hello.txt.

**Comment by SergiusTheBest** [comment]
Yes, it's because `TxtFormatter` doesn't output file name. You need to write your own formatter.

**Comment by SergiusTheBest** [comment]
PLOG_CAPTURE_FILE enables file name information in `Record`.

**Comment by Django-xinfa** [comment]
> TxtFormatter

It's OK. Thanks.
