### ISSUE TITLE
plog fails to compile on Windows with Visual Studio 2019 16.3 

### ISSUE THREAD

**Issue by jeffrosenthal** [SergiusTheBest/plog#146]
I do not find this to be a closed issue but what you provided as using Conformance mode off to be a workaround.

I am finding that using conformance mode off results in some installations the C# assembly is not able to load the c++ with plog.

Is there a better fix for this?

**Comment by SergiusTheBest** [comment]
Yeap, I'm working on it. This mode is set by default for new Visual Studio versions:

> By default, the /permissive- option is set in new projects created by Visual Studio 2017 version 15.5 and later versions. It is not set by default in earlier versions.

**Comment by SergiusTheBest** [comment]
@jeffrosenthal Now it should be fine. Please check it.

**Comment by SergiusTheBest** [comment]
I assume that everything is fine. If not please reopen the issue.
