### ISSUE TITLE
Change Log File Name

### ISSUE THREAD

**Issue by dbots94** [SergiusTheBest/plog#147]
I just started using your library since the boost one was too complicated to work with.
Sorry if this question is too simple but i can't find how to work with plog::util::nchar.

I want to be able to specify the file's name with some datetime incorporated.
For example, i would like to have this file name: "**Server_20191031131015**" where the number "_20191031131015_" corresponds to the date _2019/10/31 13:10:15._

How can I do it?

**Comment by SergiusTheBest** [comment]
Here is a sample code, it uses [strftime](http://www.cplusplus.com/reference/ctime/strftime/) to format a string with time:
```cpp
// get time
plog::util::Time time;
plog::util::ftime(&time);

// parse time
tm t;
plog::util::localtime_s(&t, &time.time);

// format string
const int kBufLen = 100;
char logFileName[kBufLen];
strftime(logFileName, kBufLen, "Server_%Y%m%d.txt", &t);

plog::init(plog::debug, logFileName);
```
Refer to strftime format specification for the date format you want.

**Comment by dbots94** [comment]
Worked just fine. Thanks for the reply and for this amazing library. 
Best regards
