### ISSUE TITLE
support show thread name

### ISSUE THREAD

**Issue by wjx0912** [SergiusTheBest/plog#149]
in windows, we can set thread name by: SetThreadDescription(GetCurrentThread(), L"ThisIsMyThreadName!")
and linux: prctl(PR_SET_NAME , (char*)name);

so, does plog support show thread name in log file? thanks

**Comment by SergiusTheBest** [comment]
Currently plog doesn't support this feature. But it sounds interesting. Thanks for the hint!

**Comment by wjx0912** [comment]
thank you.

**Comment by wjx0912** [comment]
SetThreadDescription/GetThreadDescription, only support  after Windows 10, version 1607; and vs2017+  support

**Comment by wjx0912** [comment]
SetThreadName() support vs2015, 

linux: prctl()/pthread_setname_np()

**Comment by wjx0912** [comment]
https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-set-a-thread-name-in-native-code?view=vs-2015&redirectedfrom=MSDN
