### ISSUE TITLE
Severity level from string? 

### ISSUE THREAD

**Issue by KarateSnowMachine** [SergiusTheBest/plog#15]
I'm writing some code where I want to be able to set the severity at runtime based on an input parameter. Looking at Severity.h, I see that there is a way to convert from a Severity to a string, but there is no way to get a Severity from a string. 

Obviously I could write my own function to do such a conversion, but do you think it would be valuable to provide such a conversion inside of plog itself? That is, something like: `plog::Severity severity_from_string(const string &severity_str)`

**Comment by SergiusTheBest** [comment]
Hi!

Usually I use an integer to configure the log severity level. But a string makes sense too. Do you need it to be case insensitive?

**Comment by KarateSnowMachine** [comment]
For the time being, I wrote a quick free function outside of plog that just does straight string `==` comparisons. 

I initially wanted to do case-insensitive compares but after looking online for how to do it "correctly" in C++ I decided it looked too hairy for a first pass.

**Comment by SergiusTheBest** [comment]
I've added `severityFromString` function. Please, check it.

**Comment by KarateSnowMachine** [comment]
Looks good! Thanks.
