### ISSUE TITLE
Support changing log file after plog::init

### ISSUE THREAD

**Issue by hustfox** [SergiusTheBest/plog#151]
In my program , I have many items to test serially. In order to make it easier to find the relative log, I want to log each item to a log file whose name maybe \<itemname>+\<datetime>.log etc. 

However, right now if I plog::init with different filenames, the logs are all logged into the first Init file repeately.

**Comment by SergiusTheBest** [comment]
Yes, this is a TODO item. For now you can use a solution from #62.

**Comment by SergiusTheBest** [comment]
Duplicate of #62

**Comment by SergiusTheBest** [comment]
I'm closing this issue, the progress will be tracked in #62.
