### ISSUE TITLE
use the same instance between dll & exe

### ISSUE THREAD

**Issue by wjx0912** [SergiusTheBest/plog#152]
please see #96 

i'm work on vs2019, at application start, i init plog, but when log at dll module, it not write normal.

i debug the source, find  the instance  id error in dll module, and find the patch, can you merge and release a new version.

thanks~~~

**Comment by variar** [comment]
Hi,
The approach in chained example is working pretty well for my projects
https://github.com/SergiusTheBest/plog/tree/master/samples/Chained

What do you mean by "it not write normal"?

**Comment by wjx0912** [comment]
hi, @variar 

thanks for your reply, in your dll project, the initialize() also do plog::init, otherwise the log file not write normal.
it's burden for user, does some way to remove the plog:init in dll entry?
thanks.
best regards,
