### ISSUE TITLE
add raw interface

### ISSUE THREAD

**Issue by wjx0912** [SergiusTheBest/plog#153]
can you add a raw interface:
PLOG_RAW << "\nabc123\n";

thanks

**Comment by wjx0912** [comment]
this code only output  "\nabc123\n"  to the logfile,  no other info(date,time,funcname,line),
sometime i'm not need the info.

thanks

**Comment by SergiusTheBest** [comment]
If you need raw console output you can use 2 separate loggers and `MessageOnlyFormatter`: 

```cpp
enum
{
    kRaw = 1
};

static plog::ConsoleAppender<plog::TxtFormatter> consoleAppender;
plog::init(plog::debug, &consoleAppender);

static plog::ConsoleAppender<plog::MessageOnlyFormatter> consoleAppenderRaw;
plog::init<kRaw>(plog::debug, &consoleAppenderRaw);

PLOGI_(kRaw) << "Start! (raw message)";

for (int i = 0; i < 100; ++i)
{
    PLOGI << "i: " << i;
}

PLOGI_(kRaw) << "Finish! (raw message)";
```

In other cases have non-uniform messages are discouraged as it makes log parsing painful.

**Comment by wjx0912** [comment]
thanks
