### ISSUE TITLE
ColorConsoleAppender is not compileable under Linux

### ISSUE THREAD

**Issue by Ogudikov** [SergiusTheBest/plog#154]
Compilation the following code fragment form your manual 
```
static plog::RollingFileAppender<plog::CsvFormatter> fileAppender("MultiAppender.csv", 8000, 3); // Create the 1st appender.
static plog::ConsoleAppender<plog::TxtFormatter> consoleAppender; // Create the 2nd appender.
plog::init(plog::debug, &fileAppender).addAppender(&consoleAppender); // Initialize the logger with the both appenders.
```
fails with 

> error: 'ColorConsoleAppender' in namespace 'plog' does not name a template type

c++ (Debian 8.3.0-6) 8.3.0

**Comment by Ogudikov** [comment]
SSEEE:
```
#include <plog/Log.h>
int main(){
    static plog::RollingFileAppender<plog::CsvFormatter> fileAppender("MultiAppender.csv", 8000, 3); // Create the 1st appender.
    static plog::ConsoleAppender<plog::TxtFormatter> consoleAppender; // Create the 2nd appender.
    plog::init(plog::debug, &fileAppender).addAppender(&consoleAppender); // Initialize the logger with the both appenders.
}
```
Output:

> $ c++ -I/home/ur/git/plog/include plog_test.cpp -o plogtest
> plog_test.cpp: In function 'int main()':
> plog_test.cpp:4:18: error: 'ConsoleAppender' in namespace 'plog' does not name a template type
>      static plog::ConsoleAppender<plog::TxtFormatter> consoleAppender; // Create the 2nd appender.
>                   ^~~~~~~~~~~~~~~
> plog_test.cpp:4:12: note: suggested alternative: 'RollingFileAppender'
>      static plog::ConsoleAppender<plog::TxtFormatter> consoleAppender; // Create the 2nd appender.
>             ^~~~
>             RollingFileAppender
> plog_test.cpp:5:57: error: 'consoleAppender' was not declared in this scope
>      plog::init(plog::debug, &fileAppender).addAppender(&consoleAppender); // Initialize the logger with the both appenders.
>                                                          ^~~~~~~~~~~~~~~
> plog_test.cpp:5:57: note: suggested alternative: 'fileAppender'
>      plog::init(plog::debug, &fileAppender).addAppender(&consoleAppender); // Initialize the logger with the both appenders.
>                                                          ^~~~~~~~~~~~~~~
>                                                          fileAppender
>

**Comment by SergiusTheBest** [comment]
You need to include an appropriate header:
```
#include <plog/Appenders/ColorConsoleAppender.h>
``` 
See https://github.com/SergiusTheBest/plog/blob/master/samples/ColorConsole/Main.cpp

**Comment by Ogudikov** [comment]
Yes, this works. Thanks.
On Windows (VS 2017) it works without this second include, however.
