### ISSUE TITLE
console color cannot reset

### ISSUE THREAD

**Issue by yangxingpping** [SergiusTheBest/plog#157]
centos6.6  gcc 4.4.7 when config with color consle log out, an run app and print out error and warn info.
after app exit, all string display in current console session text color become yellow.

**Comment by SergiusTheBest** [comment]
How do you exit from app? Ctrl+c?

**Comment by yangxingpping** [comment]
use ctrl+c,  then should use command like ls  to reset it , but commands like make clean, make , clear  has no effect.

**Comment by SergiusTheBest** [comment]
`Ctrl+c` terminates program execution, so no cleanup code is called. You need to add `SIGINT` handler into your app and provide a graceful shutdown. For example:
```cpp
#include <signal.h>
#include <stdlib.h>
#include <stdio.h>

static volatile sig_atomic_t keep_running = 1;

static void sig_handler(int dummy)
{
    (void)dummy;
    keep_running = 0;
}

int main(void)
{
    signal(SIGINT, sig_handler);

    while (keep_running)
        puts("Still running...");

    puts("Stopped by signal `SIGINT'");
    return EXIT_SUCCESS;
}
```
In such case everything will be fine.

**Comment by yangxingpping** [comment]
I will try tomorrow.
