### ISSUE TITLE
Changes in Plog/Util.h for rtems 

### ISSUE THREAD

**Issue by vishav26** [SergiusTheBest/plog#158]
I updated the rtems toolchain to version 5. While compiling the applications which use plog, the compiler complains for the missing timing functions which are part of sys/time.h.
Also, the compiler compains about private variable **m_sync** which cannot be typecasted to  pthread_mutex_t. 
I did the changes in the mirrored branch and the compilation works. I would like to propose the same changes on the master branch.

**Comment by SergiusTheBest** [comment]
Sure. Send your PR or a patch!

**Comment by vishav26** [comment]
Hi @SergiusTheBest . While pushing a new branch I am getting error. ERROR: Permission to SergiusTheBest/plog.git denied to vishav26. Do I have the rights to push a branch?

**Comment by SergiusTheBest** [comment]
You need to make a fork and push the changes to your fork. Then you'll have an option to create PR.
