### ISSUE TITLE
plog::Logger construction problem

### ISSUE THREAD

**Issue by mdevans** [SergiusTheBest/plog#16]
Please could you explain under what circumstances will the logger not be constructed correctly? (I am using plog in an injected dll)

Code is as per docs:

```
plog::init(plog::verbose, logFilename, LOG_FILE_SIZE, NO_OF_LOG_FILES);
DebugTrace(L"plog::get<0>=%p", plog::get<0>());

Output:
plog::get<0>=0000000000000000
```
I inserted trace statements into object constructors and determined that plog::init is being called ok but Logger constructor is not. Debug output shows LOGGER INIT but not LOGGER CONSTRUCTOR from edits below. Why?

```
inline Logger<instance>& init(Severity maxSeverity = none, IAppender* appender = NULL)
 {
  static Logger<instance> logger(maxSeverity);

  OutputDebugStringW(L"LOGGER INIT");

  return appender ? logger.addAppender(appender) : logger;
}

Logger(Severity maxSeverity = none) : m_maxSeverity(maxSeverity)
{
  OutputDebugStringW(L"LOGGER CONSTRUCTOR");
}
```

**Comment by SergiusTheBest** [comment]
Hi @mdevans 

It's very interesting. Could you provide a complete code sample? Or at least describe when do you call `plog::init` and what compiler do you use?

**Comment by mdevans** [comment]
Thanks for your response. I am using VS2015 C++ compiler. I am using a the reflective dll injection technique as described by Dan Staples here: https://github.com/dismantl/ImprovedReflectiveDLLInjection. If you call plog::init within his "MyFunction()" (delayed dll init after dllmain()) the problem occurs. If I use standard injection technique using CreateRemoteThread() plog::init works ok. Curious...

**Comment by SergiusTheBest** [comment]
I did a little research and found out:

1. VS2015 implements thread-safe static variables initialization with the help of a thread-local storage (TLS).
2. ReflectiveLoader doesn't process TLS callbacks in the DLL image.

As the result constructors of static variables are not called.

Workaround: Use `/Zc:threadSafeInit-` compiler switch to turn off thread-safe static variables initialization.

**Comment by mdevans** [comment]
Fascinating... thank-you very much Sergius, makes complete sense now.
