### ISSUE TITLE
RollingFileAppender maxFileSize type cast error x64 build

### ISSUE THREAD

**Issue by hdhog** [SergiusTheBest/plog#160]
maxFileSize is `size_t` but casting to `long`

![image](https://user-images.githubusercontent.com/386666/74762201-cad8cf80-5296-11ea-9dcc-8a6f9a445820.png)

**Comment by SergiusTheBest** [comment]
Do you need support for files > 2GB?

**Comment by hdhog** [comment]
yes. log needed splitting to parts on 2Gb.

**Comment by SergiusTheBest** [comment]
@hdhog The issue is fixed in the `develop` branch. Please check it out.
