### ISSUE TITLE
more customizable ColorConsoleAppender

### ISSUE THREAD

**Issue by ilya-rusyanov** [SergiusTheBest/plog#163]
In order to customize color output I would like to make messages appear in form

`app-name 2020-04-06 13:08:31.831 INFO [2721] [func@100]`

however, in ColorConsoleAppender.h setColor() and resetColor() are defined as private for some reason. If one would be eager to override just write() call, he has no chance to reuse color methods. Is it possible to make them protected? Or is there any other way round?

**Comment by SergiusTheBest** [comment]
Good point! Yes, protected is fine.

**Comment by SergiusTheBest** [comment]
Send PR if you have one.

**Comment by ilya-rusyanov** [comment]
Thank you. Unfortunately did not have time for that simple feature. Sorry for that
