### ISSUE TITLE
_if_not_exists error

### ISSUE THREAD

**Issue by SamiraMHosseini** [SergiusTheBest/plog#165]
I wrote a simple program and got lots of errors while trying to compile it? I added the path of header files to the project include path and the code should be working, but all errors are mentioned to line including "LOGD << "main() called".

How should I fix them?

> syntax error: missing ')' before identifier '__if_not_exists'    
>  
> 'this': can only be referenced inside non-static member functions or non-static data member initializers.
>  
> Error C2065:    '__if_exists': undeclared identifier
>  
>  
> Warning    C26812    The enum type 'plog::Severity' is unscoped. Prefer 'enum class' over 'enum' (Enum.3).    
>         

```
#include <iostream>
#include <plog/Log.h> // Step 1: include the logger header
int getUserInput()
{
	LOGD << "getUserInput() called"; // LOGD is defined by the plog library

	std::cout << "Enter a number: ";
	int x{};
	std::cin >> x;
	return x;
}

int main()
{
	plog::init(plog::debug, "Logfile.txt"); // Step 2: initialize the logger

	LOGD << "main() called"; // Step 3: Output to the log as if you were writing to the console

	int x{ getUserInput() };
	std::cout << "You entered: " << x;

	return 0;
}
```

**Comment by SergiusTheBest** [comment]
Are you using 1.1.15 version of plog?

**Comment by SamiraMHosseini** [comment]
I clicked on the "latest version" tag and the download "source code.zip", which turns out to be plog-1.1.4.
I downloaded some hour ago. I am using Windows 10 and Microsoft Visual Studio Community 2019.

**Comment by SergiusTheBest** [comment]
Oh, I've updated the latest release to 1.1.5. Use it, the issue is resolved there.

**Comment by SamiraMHosseini** [comment]
Thank you so much. 
My problem has been solved!
Just one more question:
For this library Plog, we only need to include the path to _Include Directories_ of IDE, right? Because for some other libraries we need to include path to the lib files in _Library Directories_

**Comment by SergiusTheBest** [comment]
This is a header-only library, so only include path is required.
