### ISSUE TITLE
Error: ::_wsopen_s has not been defined

### ISSUE THREAD

**Issue by brennan-macaig** [SergiusTheBest/plog#17]
Relevant section from my console output on compile

    C:\Users\heybr\plog-1.0.1\include/plog/Util.h:220:17: error: '::_wsopen_s' has not been declared
                 ::_wsopen_s(&m_file, fileName, _O_CREAT | _O_WRONLY | _O_BINARY, _SH_DENYWR, _S_IREAD | _S_IWRITE);
                 ^

Code used is the hello log code from the readme, compiled on MinGW G++

**Comment by SergiusTheBest** [comment]
Hi @brennan-macaig,

Please, try the latest version from the master and tell if everything is ok.

**Comment by brennan-macaig** [comment]
@SergiusTheBest Sorry I wasn't able to test this earlier. It works just fine now! Thanks!

Happy hacking in 2016!

**Comment by SergiusTheBest** [comment]
Thank you too! Happy New Year!
