### ISSUE TITLE
cmake deprecation warning

### ISSUE THREAD

**Issue by hanseuljun** [SergiusTheBest/plog#175]
I'm using CMake 3.19.1 and this message comes up. It is an easy fix, just bumping up the min cmake version, but leaving here since I was not sure whether you were intentionally keeping the min version low.

![image](https://user-images.githubusercontent.com/5001447/101843137-670de480-3afe-11eb-9b97-51a01d935f22.png)

**Comment by SergiusTheBest** [comment]
Thank you for reporting this! 

2.8 is the default version on Ubuntu 14.04. There is no needs to keep it now.
