### ISSUE TITLE
endl Not crlf On Windows

### ISSUE THREAD

**Issue by btribley** [SergiusTheBest/plog#179]
<< endl 
on Windows should be crlf. It's lf as if it were unix. I don't see any way to set it. This includes the end of lines generated by the program after each entry. Am I missing something?

**Comment by SergiusTheBest** [comment]
It's converted to crlf by [NativeEOLConverter](https://github.com/SergiusTheBest/plog/blob/master/include/plog/Converters/NativeEOLConverter.h) if you write it to a file.

**Comment by btribley** [comment]
I just use the defaults, don't specify any converter:
plog::init(plog::verbose, (AppData::aconfig.startupDir + 
			AppData::lConfig.engineLogFname).c_str(), logFileSize, logFileCt);
			
So the default file writers don't convert?  I will look into this some more. Thanks for the quick reply.

**Comment by SergiusTheBest** [comment]
It is used by default since version 1.1.5.
