### ISSUE TITLE
Zip download Init() is Broken

### ISSUE THREAD

**Issue by btribley** [SergiusTheBest/plog#180]
Feeling silly for not having pulled down the latest version I did so, renamed the previous and dropped this in. Boom, got this compiler error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2660	'plog::init': function does not take 4 arguments	MachPlantSimEngine	c:\users\public\dev\machplantsimapp\machplantsimengine\machplantsimengine.cpp	48	
```

Looked and Init.h has a lot less code in it. I tried patching the old Init.h in and got a slew of other errors, figured this was a bad thing but had to be sure. 

My init hasn't changed and is identical to the one in Readme.md that calls for 4 parameters:
`Logger& init(Severity maxSeverity, const char/wchar_t* fileName, size_t maxFileSize = 0, int maxFiles = 0);` 
I am definitely not doing anything advanced, just want a basic logger. 

What am I missing?

**Comment by SergiusTheBest** [comment]
The init code was split up into several headers to minimize mandatory dependencies. You need to add `#include <plog/Initializers/RollingFileInitializer.h>`.

**Comment by btribley** [comment]
This fixed it: 
`#include "../plog-master/include/plog/Initializers/RollingFileInitializer.h"`
Thank you for your help!
