### ISSUE TITLE
README.MD

### ISSUE THREAD

**Issue by LukashonakV** [SergiusTheBest/plog#182]
Usage section has got a mistake.

_Step 1: Adding includes

At first your project needs to know about plog. For that you have to:

    Add plog/include to the project include paths
    Add #include <plog/Log.h> into your cpp/h files (if you have precompiled headers it is a good place to add this include there)

Step 2: Initialization

The next step is to initialize the Logger. This is done by the following plog::init function:_

*****
But without #include "plog/Initializers/RollingFileInitializer.h" you are not able to use plog::init

Please fix readme.

**Comment by SergiusTheBest** [comment]
Yes, thank you for noticing that!

**Comment by sehoffmann** [comment]
I came here to report the same. Please consider updating the readme to make the library easier accessible.

**Comment by SergiusTheBest** [comment]
Fixed by #169
