### ISSUE TITLE
Compilation error when outputting std::filesystem::paths

### ISSUE THREAD

**Issue by rockaport** [SergiusTheBest/plog#185]
If you output filesystem::paths the compiler throws an error:

`Record.h:201: error: use of overloaded operator '<<' is ambiguous (with operand types 'util::nostringstream' (aka 'basic_ostringstream<char>') and 'const std::filesystem::__cxx11::path')`

I have to go around adding `.string()`  to all my paths I want to print.

Great library though!

**Comment by SergiusTheBest** [comment]
Thanks! What compiler do you use?

**Comment by rockaport** [comment]
Good point, I'm using clang version 10.0.0-4ubuntu1
It looks like it's not a problem when I swing to GNU c++ (Ubuntu 9.3.0-10ubuntu2)
I'm using the Android NDK too, which is based off of clang.

**Comment by SergiusTheBest** [comment]
Ok, I'll check it out.

**Comment by SergiusTheBest** [comment]
@rockaport It's fixed now. Please test it on your side.

**Comment by rockaport** [comment]
@SergiusTheBest works perfectly thanks!
