### ISSUE TITLE
Truncating file when creating RollingFileAppender?

### ISSUE THREAD

**Issue by KarateSnowMachine** [SergiusTheBest/plog#19]
Is there a way to truncate an existing log file when creating a RollingFileAppender? That is, I have a foo.log from a previous execution and when I execute the program again, I want foo.log to be overwritten. 

It appears that plog specifically seeks to the end of the file when opening it. Is it worthwhile to have a flag that overrides this behavior?

**Comment by SergiusTheBest** [comment]
Truncating a file you loses previous log entries. This is not good: imagine an application that crashed and restarted - all logged information is lost in such case.
What problem do you want to solve with truncation? Maybe there is an another solution?

**Comment by KarateSnowMachine** [comment]
Our logs tend to be transient -- they are only relevant for any given run of the program (we aren't using plog for a long-running daemon or server application or anything like that). When we run interactively, there's really no reason for us to save log messages from previous runs. When we run in batch, we save the logs to different directories, so this isn't an issue. 

I realize this is probably very different than how others use this library. For our internal plog, I've added `O_TRUNC` to open just to force this behavior. I was just wondering if you saw any value into having this option available upstream. Perhaps as a different Appender? If not, that's understandable, you can close this issue.

**Comment by SergiusTheBest** [comment]
I see now. It makes sense in your case but it's not common. I'm closing the issue but thanks anyway!
