### ISSUE TITLE
QStringRef removed in Qt6

### ISSUE THREAD

**Issue by macdew** [SergiusTheBest/plog#190]
QStringRef has been removed in Qt6, which breaks the default Qt integration for plog.  It would be good to either guard the operator<<(const QStringRef& data) with a Qt version check, or do something else to guard against this?

**Comment by SergiusTheBest** [comment]
Thanks for reporting!

**Comment by macdew** [comment]
No worries!  I think it should be possible to guard the QStringRef operator with something like...
#if QT_VERSION < 0x060000
   ... operator here
#endif
