### ISSUE TITLE
codeblocks  compile error on ColorConsole sample

### ISSUE THREAD

**Issue by jeajohn-kuo** [SergiusTheBest/plog#191]
Hi,

I am trying to use codeblocks 20 to copile ColorConsole ，but get errors .

||=== Build: Release in aaaaa (compiler: GNU GCC Compiler) ===|
C:\TEMP\gjztimer\test-log\plog-1.1.5\include\plog\Appenders\ConsoleAppender.h||In constructor 'plog::ConsoleAppender<Formatter>::ConsoleAppender()':|
C:\TEMP\gjztimer\test-log\plog-1.1.5\include\plog\Appenders\ConsoleAppender.h|14|warning: there are no arguments to '_fileno' that depend on a template parameter, so a declaration of '_fileno' must be available [-fpermissive]|
C:\TEMP\gjztimer\test-log\plog-1.1.5\include\plog\Appenders\ConsoleAppender.h||In instantiation of 'plog::ConsoleAppender<Formatter>::ConsoleAppender() [with Formatter = plog::TxtFormatter]':|
C:\TEMP\gjztimer\test-log\plog-1.1.5\include\plog\Appenders\ColorConsoleAppender.h|12|required from 'plog::ColorConsoleAppender<Formatter>::ColorConsoleAppender() [with Formatter = plog::TxtFormatter]'|
C:\TEMP\gjztimer\aaaaa\main.cpp|10|required from here|
C:\TEMP\gjztimer\test-log\plog-1.1.5\include\plog\Appenders\ConsoleAppender.h|14|error: '_fileno' was not declared in this scope|
||=== Build failed: 1 error(s), 4 warning(s) (0 minute(s), 1 second(s)) ===|

Many thanks :)

**Comment by SergiusTheBest** [comment]
Are you using mingw64 or what exactly?

**Comment by jeajohn-kuo** [comment]
I  got the same error  when i use   CodeBlock 20（mingwin32） or CodeBlock 17 （mingwin32） or  Codeblock13（mingwin32）.

**Comment by SergiusTheBest** [comment]
Could you run `g++ --version` and post its output here?

**Comment by SergiusTheBest** [comment]
I installed CodeBlock 20（mingwin32）and it compiled fine. `g++ --version` output is:
```
c:\Program Files (x86)\CodeBlocks\MinGW\bin>g++ --version
g++ (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 8.1.0
```

**Comment by jeajohn-kuo** [comment]
i check my compiler,  it's my mistake .   when i set std=gnu++11, it work well.  thank u.

**Comment by SergiusTheBest** [comment]
Ok, no problem.
