### ISSUE TITLE
When I initialize plog with the same file in three dynamic libraries and load them, it occurs overwrite phenomenon.

### ISSUE THREAD

**Issue by zj1838277795** [SergiusTheBest/plog#193]
Is it not supported to initialize a file more than once?

**Comment by SergiusTheBest** [comment]
Yes, it's not supported as file rolling will require extra synchronization in such case. You can do the following:

- use different file names for different libraries
- use a centralized file logger and push log messages from libraries to it (see [Chained Loggers](../#chained-loggers) for more info)
