### ISSUE TITLE
can printf like style with not auto ‘\n’?

### ISSUE THREAD

**Issue by jcyhcs** [SergiusTheBest/plog#197]
hi,professor:
i use your plog library, it work well. but there is a question:
code like this:
uchar buf[7] = {0xA9 0x9A 0x03 0x01 0x00 0xAA 0x99};
					for(int i = 0;i < 7;i++) {
						PLOGI.printf("%02x ",buf[i]);
					}
i want to log like:  "A9 9A 03 01 00 AA 99",BUT! PLOGI auto add '\n', so it look:
A9
9A
03
01
00
AA
99

so, please HELP ME! how can i do??

**Comment by SergiusTheBest** [comment]
Hi!

You need to create a string with the whole message and then send it to PLOGI:
```cpp
unsigned char buf[7] = { 0xA9, 0x9A, 0x03, 0x01, 0x00, 0xAA, 0x99 };

std::stringstream ss;

for (int i = 0; i < 7; i++) {
  ss << std::setfill('0') << std::setw(2) << std::hex << static_cast<int>(buf[i]) << " ";
}

PLOGI << ss.str();
```
If you need it often you can create a custom type handler:
```cpp
namespace plog {
    template<size_t N>
    Record& operator<<(Record& record, const unsigned char (& buf)[N]) {
        for (int i = 0; i < N; i++) {
            record << std::setfill(PLOG_NSTR('0')) << std::setw(2) << std::hex << static_cast<int>(buf[i]) << " ";
        }

        return record;
    }
}

unsigned char buf[7] = { 0xA9, 0x9A, 0x03, 0x01, 0x00, 0xAA, 0x99 };
PLOGI << buf;
```

**Comment by SergiusTheBest** [comment]
Marking this issue as resolved. If you have any more questions please ask.
