### ISSUE TITLE
MSVC SDK 10.0.19041.0 incompatibility

### ISSUE THREAD

**Issue by lordvictory** [SergiusTheBest/plog#198]
Was looking for a small standard C++ logger to integrate into my C++ project so I thought I'd try to use yours.  I took your sample ColorConsole and added the logic into my program, but received compilation failures.  So I created a small test case using you sample that isolates the problem.

If you take your sample program and simply add the following before main but after including your files:

```cpp
// libcurl definitions
namespace curl {
namespace lib {
#include <curl/curl.h>
}
}
```

This simply includes the standard libcurl include files, wrapping them in a namespace.

Unfortunately, it appears your definitions of numerous Windows API's are clashing with the SDK definitions, resulting in many error messages like the following:

C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\synchapi.h(117): error C2116: 'plog::InitializeCriticalSection': function parameter lists do not match between declarations

My build environment is:

Windows 10
Version 16.11.5
VisualStudio.16.Release/16.11.5+31729.503
Microsoft .NET Framework
Version 4.8.04084
Installed Version: Enterprise
Visual C++ 2019   00435-60000-00000-AA788
Microsoft Visual C++ 2019
Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

All code is being built from the standard MSVC x64 command prompt provided from VS.

**Comment by SergiusTheBest** [comment]
Marking this issue as resolved. If you have any more questions please ask.
