### ISSUE TITLE
Error macro

### ISSUE THREAD

**Issue by fabri8bit** [SergiusTheBest/plog#2]
Hi,
I use CLION JetBrains IDE C / C ++.

1) plog::init(plog::info, x.substr(6, x.size()).append("/").append("createfp.log").c_str());

2) LOGI << "INIT\n";  
....
The compile and run program is ok. but there is program :

Problem synopsis   Error after macro substitution: Pointer type is required at line xxxx

Help me?
Thanks.

**Comment by SergiusTheBest** [comment]
Hi,

This is a false positive in CLion's code inspection (it doesn't parse a template function correctly). What I can do is to report it to their bugtracker and hope that they'll fix it.

**Comment by SergiusTheBest** [comment]
The bug is open since 2013: https://youtrack.jetbrains.com/issue/CPP-3601

**Comment by SergiusTheBest** [comment]
Fixed in CLion 1.0.5.
