### ISSUE TITLE
Plog in library

### ISSUE THREAD

**Issue by sindney** [SergiusTheBest/plog#20]
Hi, i'm trying to init plog in both my library and demo executable. Like this:
```
plog::init(plog::warning, FileUtil::Instance()->GetAbsPath("Log.txt").c_str()).addAppender(
	new plog::ConsoleAppender<plog::FuncMessageFormatter>());
// my library using plog
Engine::InitPlog(plog::warning, plog::get());
// Engine::initPlog function
static void InitPlog(plog::Severity severity, plog::IAppender* appender)
{
	plog::init(severity, appender);
}
```
On windows everything is fine, but the same code report errors on osx.
`Assertion failed: (appender != this), function addAppender, file /Users/xinhou/Documents/Sdk/Plog/include/plog/Logger.h, line 18.`

Compiler: 
Apple LLVM version 7.0.2 (clang-700.1.81)

What could possiblly be wrong ?

**Comment by SergiusTheBest** [comment]
Hi, there!

It looks that your library is a shared object and visibility is set to default (thus all symbols are exported and plog instance is the same for executable and library). You can do one of the following:
* set visibility to hidden `clang -fvisibility=hidden` and explicitly export required symbols using `__attribute__ ((visibility ("default")))`
* do not call `plog::init` in OSX library version (as plog instance from your executable is used and `plog::init` is already called for it)
* use another plog instance in your library (see [MultiInstance/Main.cpp](https://github.com/SergiusTheBest/plog/blob/master/samples/MultiInstance/Main.cpp))

**Comment by sindney** [comment]
Got it! Thanks
