### ISSUE TITLE
How can I set different severities for different appenders?

### ISSUE THREAD

**Issue by relishou** [SergiusTheBest/plog#201]
How can I set different severities for different appenders in a same logger?

**Comment by SergiusTheBest** [comment]
Take a look at #181. I'll add it to the documentation.

**Comment by SergiusTheBest** [comment]
I'm closing this. If you have any questions feel free to ask.

**Comment by SergiusTheBest** [comment]
I'm closing this. If you have any questions feel free to ask.

**Comment by relishou** [comment]
Thanks, understand!
