### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by gouarin** [SergiusTheBest/plog#204]
Hello,

thanks for this nice project. I was looking for a log library that does not degrade the performance of a numeric code when logs are not enabled and it seems that plog does it perfectly.

So I would like to create a conda package. I see that the last release is almost a year old now. Would it be possible to make a new one in order to have an up-to-date package?

I will be able to keep building the package according to the new releases.

**Comment by SergiusTheBest** [comment]
Hi @gouarin ,

Yes, but I need to update the documentation first. I'll try to do that in the next few days.

**Comment by gouarin** [comment]
Thanks @SergiusTheBest.

**Comment by SergiusTheBest** [comment]
Release is ready: https://github.com/SergiusTheBest/plog/releases/tag/1.1.6

**Comment by gouarin** [comment]
plog is now on conda-forge https://anaconda.org/conda-forge/plog

I will open a new PR soon to add the material to be able to make `FindPackage(plog)`in a CMakeLists.txt.

**Comment by gouarin** [comment]
Thanks. I will take a look then.
