### ISSUE TITLE
how could i output(log) the filename ?  by the field m_file of class Record ?

### ISSUE THREAD

**Issue by yugengde** [SergiusTheBest/plog#205]

**Comment by SergiusTheBest** [comment]
Yes. There is `getFile()` method. Use it in your formatter class. Also you need to define `PLOG_CAPTURE_FILE` to enable capturing of the file names.

**Comment by ahanin-emerson** [comment]
I have tried doing that, both the formatter with the getFile() method and the define, but it still comes up as an empty string

**Comment by SergiusTheBest** [comment]
@ahanin-emerson Where do you define PLOG_CAPTURE_FILE? It should be defined before including plog headers or it the project settings.

**Comment by ahanin-emerson** [comment]
Oh! okay, yes, I defined it after the include and not before, my bad.
Thanks for the super quick reply!

**Comment by SergiusTheBest** [comment]
@ahanin-emerson No problem!
