### ISSUE TITLE
__FILE__

### ISSUE THREAD

**Issue by stephane-martin** [SergiusTheBest/plog#21]
Hello !

Is there any reason why the LOG_ macro (and the LogRecord object) does not record the original file where the LOG_ statement happened, using **FILE** ?

Thank you

**Comment by SergiusTheBest** [comment]
Hi!

Actually I tried to use it in the past and got the following results:

* `__FILE__` cases full file paths to be present in a binary (that is not desirable)
* In most cases a function name gives more meaningful information than a file name

So I decided to drop `__FILE__` in favor of `__FUNC__`. 

If you have any thoughts about this please share.

**Comment by stephane-martin** [comment]
Well, my needs are rather specific... i write a Python module based on some C++ library. I use plog for the C++ part, and i need to get the logs back to the standard Python logging system (so that the end user also has to care about Python).

Somewhere in the cooking i have to build a Python LogRecord object (https://docs.python.org/2/library/logging.html#logrecord-objects). This kind of object typically references the source filename.

("__FILE__ cases full file paths to be present in a binary (that is not desirable)" -> definitely agree, thats why #line can be useful: https://gcc.gnu.org/onlinedocs/cpp/Line-Control.html#Line-Control)

**Comment by SergiusTheBest** [comment]
`#line` could help but it requires you to manually specify file names.

What if you just return an empty file name?

**Comment by stephane-martin** [comment]
well, then i don't have the C source filename in Python logs :) Right now i push __FILE__ into Record void* 'object' field, but that doesnt feel "clean".

**Comment by SergiusTheBest** [comment]
Hey, take a look at the `capture-file` branch. Will that work for you?

**Comment by stephane-martin** [comment]
Sure, thanks !

(I do think that to provide __FILE__ it's not possible to only work by inheritance, as a custom LogRecord class is not really possible for the user)

**Comment by SergiusTheBest** [comment]
@stephane-martin How is it going?

**Comment by SergiusTheBest** [comment]
Merged to master.
