### ISSUE TITLE
CMake + vcpkg: find_package

### ISSUE THREAD

**Issue by vebjornjr** [SergiusTheBest/plog#211]
Hi!

Thank you for this library.

I installed it via vcpkg (manifest mode). CMake's `find_package(plog CONFIG REQUIRED)` doesn't seem to work for me. I see that this feature has already been discussed (and implemented?) in issue #171. So I'm wondering if my issue is related to the CMake configuration in this project or with the vcpkg port.

Thank you!

**Comment by SergiusTheBest** [comment]
Hi @vebjornjr ,

Is the issue actual? Or did you manage to solve it?

**Comment by SergiusTheBest** [comment]
Indeed `find_package` doesn't work though the project compiles and can find `#include <plog/Log.h>`. It seems that vcpkg port needs to be updated to support this feature.

Thank you for reporting!

**Comment by SergiusTheBest** [comment]
Sent PR to vcpkg: https://github.com/microsoft/vcpkg/pull/25166.

**Comment by SergiusTheBest** [comment]
The fix is merged!
