### ISSUE TITLE
Compile error on C++ Builder 10.4

### ISSUE THREAD

**Issue by silversheart** [SergiusTheBest/plog#225]
Hi! Just have downloaded release 1.1.8, add include instruction and path to include. Have wrote initialization and first message, as: 

```
#include <plog/Log.h>
#include <plog/Initializers/RollingFileInitializer.h>
...
plog::init(plog::debug, "ManAcc.log", 100000000, 10);
PLOGD << "App started. Logging activated.";

```
And have next compile errors: 

**[bcc32c Error] Util.h(167): use of undeclared identifier '_vscprintf'
[bcc32c Error] Util.h(184): use of undeclared identifier '_vsnprintf_s'
[bcc32c Error] Util.h(198): use of undeclared identifier '_vscwprintf'
[bcc32c Error] Util.h(215): use of undeclared identifier '_vsnwprintf_s'**

any ideas?

**Comment by SergiusTheBest** [comment]
Unfortunately I have no C++ Builder 10.4 to check that right now. It seems it uses `vsnprintf_s` instead of `_vsnprintf_s` and there is no `_vscprintf` at all. Could you remove underscores and compile again? And replace `_vscprintf` with a constant value 0x1000.

**Comment by silversheart** [comment]
[bcc32c Error] Util.h(185): no matching function for call to 'vsnprintf_s'
  stdio.h(233): candidate function not viable: requires 4 arguments, but 5 were provided
[bcc32c Error] Util.h(199): use of undeclared identifier 'vscwprintf'
[bcc32c Error] Util.h(216): no matching function for call to 'vsnwprintf_s'
  stdio.h(235): candidate function not viable: requires 4 arguments, but 5 were provided

**Comment by SergiusTheBest** [comment]
Oh, there is another count of parameters. Replace:
```c++
int retval = _vsnprintf_s(str, bufferCharCount, charCount, format, ap);
```
with
```c++
int retval = vsnprintf_s(str, bufferCharCount, format, ap);
```
and the same for `vsnwprintf_s`.

`vscwprintf` should be replace with the constant as `_vscprintf`.

**Comment by SergiusTheBest** [comment]
I pushed the fix to the master. Please, try it.

**Comment by SergiusTheBest** [comment]
Useful info about C++ Builder (just for the reference):

- [C Run-Time Library Reference](https://docwiki.embarcadero.com/RADStudio/Sydney/en/C_Run-Time_Library_Reference)
- [Download the Free C++ Compiler](https://www.embarcadero.com/free-tools/ccompiler/free-download)
- [Using CMake with the free Embarcadero C++ compiler](https://blogs.embarcadero.com/using-cmake-with-the-free-embarcadero-c-compiler/)

**Comment by silversheart** [comment]
Yeah! All works perfect! Thanks! :)
