### ISSUE TITLE
Remove an appender?

### ISSUE THREAD

**Issue by aniongithub** [SergiusTheBest/plog#226]
I'm using plog as an internal logging library for my C API that allows users to specify log callbacks from my lib. In this case, I need the ability to remove appenders as well. This would also be true for long running microservice applications that may have clients who connect and disconnect as required and need on-demand logging capabilities.

How can I do this?

Thanks for creating plog!

**Comment by SergiusTheBest** [comment]
Could you provide more details?

**Comment by aniongithub** [comment]
Thank you for the quick reply! 

I currently add a log appender like so:
`plog::init((plog::Severity)params.logLevel, _appender.get());`

This effectively boils down to a call to [`addAppender`](https://github.com/SergiusTheBest/plog/blob/cb86692e6a4e7100729a071203a9aa96452ae791/include/plog/Logger.h#L24). How would I remove the appender I added using this method?

**Comment by SergiusTheBest** [comment]
Ok, I think I understand what do you need.

**Comment by SergiusTheBest** [comment]
I've added a DynamicAppender to keep the old behavior and add ability to add/remove appenders dynamically. Here is how to use it:
https://github.com/SergiusTheBest/plog/blob/4c7997b15a3cdc1be9c5b574849b46e32c94a445/samples/DynamicAppender/Main.cpp#L5-L30

**Comment by aniongithub** [comment]
That's perfect, thanks for this!
