### ISSUE TITLE
deactivate printf style formatting by default 

### ISSUE THREAD

**Issue by bitFiedler** [SergiusTheBest/plog#229]
Since branch 'printf-style-support' git #dc90f76042c7f3aba20ce1b36aec276a799d9b67 was merged into master. The backward compatibility was broken, because some system do not have vasprintf therefore the feature should be deactivated by default. 

I did this because that logger is running on an embedded system that do not have the vasprintf function. 

Record.h line 301 got patched with:
#if defined(PLOG_ENABLE_PRINTF) && !defined(__cplusplus_cli)

**Comment by SergiusTheBest** [comment]
Changing the existing behavior is not good. So it's better to leave it enabled and introduce the ability to disable it in specific cases.

BTW, what is you embedded platform?

**Comment by bitFiedler** [comment]
We are using STM32F7xxx with FREERTOS and LWIP

**Comment by bitFiedler** [comment]
ok that would be ok for me that there would be a Define that can be activated to disable the printf functionality

**Comment by SergiusTheBest** [comment]
> We are using STM32F7xxx with FREERTOS and LWIP

Thank you! I'm asking because I'm planning to expand the current set of CI builds.

**Comment by SergiusTheBest** [comment]
This is resolved by #243. `vasprintf` is not used anymore if it's not supplied by runtime libraries.

@bitFiedler could you confirm that?
