### ISSUE TITLE
Compilation error in VS2005

### ISSUE THREAD

**Issue by luofengBJ** [SergiusTheBest/plog#232]
In the project, I used the latest submission in the Master branch to compile in a VS2005, and he reported an error in the Record. h

record.h(63) : error C2039: 'type' : is not a member of 'plog::detail::meta::enableIf'

She seems to be a grammar problem, but I don't know how I should fix it. Please ask the author how to fix this problem. thank you

**Comment by SergiusTheBest** [comment]
I'm sorry but VS2005 is way too old to be supported. It's not present on any available build servers.

**Comment by luofengBJ** [comment]
What is the last version that supports VS2005? I used plog in a higher version of VS, which is very easy to use. But now there is an older project using VS2005. I hope to use plog in VS2005

**Comment by SergiusTheBest** [comment]
@luofengBJ I never compiled it on VS2005, the oldest I have is VS2010. You can try previous plog versions (that has no `plog::detail::meta::enableIf`). Also you can comment out problematic code.

I'll try to download VS2005 from archive.org and check it.

**Comment by SergiusTheBest** [comment]
@luofengBJ Try the version from the `msvc-2005` branch. Is it working for you?

**Comment by luofengBJ** [comment]
Thank you very much
Now I use msvc-2005 branch code to compile and use it in VS2005. It has no problem. It looks like it can run. Thank you for your modification
