### ISSUE TITLE
Logging from multiple processes into the same file

### ISSUE THREAD

**Issue by dbaumei** [SergiusTheBest/plog#235]
I adjusted the Shared sample code a little bit to test if multiple processes could write to the same file safely (on Linux/WSL, compiling with gcc).

```c++
int main()
{
    static plog::RollingFileAppender<plog::TxtFormatter, plog::UTF8Converter> fileAppender("Shared.txt", 10000, 0);
    plog::init(plog::debug, &fileAppender); // Initialize the logger.
    PLOGD << "Hello from app!"; // The message will go to the logger in this module.

    for (int i = 0; i < 1000; ++i){
        PLOG_INFO << "Heres a log entry from PID: " << getpid();
        std::this_thread::sleep_for(std::chrono::microseconds(1));
    }

    return 0;
}
```

Then I ran the same executable multiple times simultaneously:

```
./build/samples/Shared/SharedApp & ./build/samples/Shared/SharedApp & ...and a few more
```

And here's a excerpt of the log file:
```
2023-01-05 11:49:00.970 INFO  [30949] [main@32] Heres a log entry from PID: 30949
2023-01-05 11:49:00.970 INFO  [30951] [main@32] Heres a log entry from PID: 30951
2023-01-05 11:49:00.970 INFO  [30952] [main@32] Heres a log entry from PID: 30952
2023-01-05 11:49:00.970 INFO  [30946] [main@32] Heres a log entry from PID: 30946
2023-01-05 11:49:00.970 INFO  [30948] [main@32] Heres a log entry from PID: 30948
2023-01-05 11:49:00.970 INFO  [30949] [main@32] Heres a log entry from PID: 30949
2023-01-05 11:49:00.970 INFO  [30953] [main@32] Heres a log entry from PID: 30953
2023-01-05 11:49:00.970 INFO  [30952] [main@32] Heres a log entry from PID: 30952
2023-01-05 11:49:00.970 INFO  [30951] [main@32] Heres a log entry from PID: 30951
```

So for a single, non-rolling file this works like a charm.

**My question:** Is this meant to be working and is it safe to do? I.e. do the processes actually share the same logger instance? I looked into the code, but it does not seem to me that the logger or the pthread_mutex is shared across the different processes.

When I run it with different parameters for the file appender, e.g. 5 files, it odes not quite work like in the example above. I think what happens is that each process grabs its own file by rolling independently and then the files are written to by only one process.

Assuming writing to a single file from multiple processes is safe with plog: Do you have an idea how to solve the issue for rolling files? I would be happy to help implement this.

**Comment by SergiusTheBest** [comment]
Logging to the same file from multiple processes is working fine due to `O_APPEND` (each write operation is guaranteed to be atomic and to the end of the file). 

The problem is file rolling. It requires an interprocess locking mechanism. And it should be safe in case one of the processes is terminated.

Data (and code) sharing works between shared objects (*.so) in one process. Other processes are isolated and has their own data (while they can have shared code).
