### ISSUE TITLE
PLOG_ GET_ FUNC() does not support Chinese method names, can is suport?

### ISSUE THREAD

**Issue by CreatingBug** [SergiusTheBest/plog#238]
void 中文( )
{
static plog::ColorConsoleAppender<plog::TxtFormatter> appender(plog::streamStdOut);
plog::init<instanceId>(plog::debug, &appender);
PLOG << "Method name does not support Chinese。";
}

**Comment by SergiusTheBest** [comment]
@CreatingBug  What is your compiler and OS?

**Comment by CreatingBug** [comment]
> 

Number of compiled programs: 64; VS local compiler version used: 16; Windows SDK version used: 10.0.18362.0

**Comment by CreatingBug** [comment]
#define PLOG_(instanceId, severity)      IF_PLOG_(instanceId, severity) (*plog::get<instanceId>()) += plog::Record(severity, PLOG_GET_FUNC(), __LINE__, PLOG_GET_FILE(), PLOG_GET_THIS(), instanceId).ref()

You can replace "PLOG_GET_FUNC()" with "中文" and then test.

**Comment by CreatingBug** [comment]
@SergiusTheBest Thank you for your answer. What do I need to do? Will you modify it in the next release?

**Comment by SergiusTheBest** [comment]
@CreatingBug You need to compile your app with `/utf-8` and check that it doesn't break anything in your app. It affects on `char` literals in your code. In a windows app there shouldn't be much `char` literals, windows uses `wchar` instead. So it should be ok, but you need to check it anyways.

**Comment by SergiusTheBest** [comment]
@CreatingBug Did you check your app with `/utf-8`? The fix from my side is on the way and will be ready soon.

**Comment by SergiusTheBest** [comment]
@CreatingBug I've added a sample that demonstrates your use case. Compile with `/utf-8` and it shoud be fine.

https://github.com/SergiusTheBest/plog/blob/d60df3a1efa99061f637c263fe4e467c273d8655/samples/Utf8Everywhere/Main.cpp#L1-L33
