### ISSUE TITLE
Readme typo?

### ISSUE THREAD

**Issue by aisnote** [SergiusTheBest/plog#242]
From the readme:

Assume 20 **microsec** per a log call then 500 log calls per **a second** will slow down an application by 1%. It is acceptable for most use cases.

**Comment by SergiusTheBest** [comment]
What do you find wrong there?

**Comment by aisnote** [comment]
I dont understand how come out: 500 log calls per a sencod to slow down 1% 
> 500 * 20 microsec = 10,000 millisec

**Comment by SergiusTheBest** [comment]
500 * 20 microsec = 10,000 microsec = 10 millisec

**Comment by SergiusTheBest** [comment]
1 sec = 1000 millisec, 10 / 1000 = 0.01 = 1%

**Comment by SergiusTheBest** [comment]
I hope now everything is clear so I'm closing the issue.

**Comment by aisnote** [comment]
thanks
