### ISSUE TITLE
[Feature Request] std::string to plog::nstring/plog::nchar

### ISSUE THREAD

**Issue by Icyfiremario** [SergiusTheBest/plog#254]
I want to be able to use a filename I generated that contains the date and the time using boost::date_time() but it is type std::string while the data type required for the filename in plog::init is plog::nchar.

**Comment by Icyfiremario** [comment]
Nvm figured out how to convert using some type casting, I was just not thinking properly.

Implementation for anyone who needs it:

std::string str;
const plog::util:nchar* char = str.c_str();

**Comment by SergiusTheBest** [comment]
@Icyfiremario Yes, you just use `.c_str()`, for example: `plog::init(plog::debug, filename.c_str());`
