### ISSUE TITLE
How can I dynamically create a Logger object?

### ISSUE THREAD

**Issue by yangxq5858** [SergiusTheBest/plog#257]
How can I dynamically create a Logger based on the passed file path, file name, and message level? I'm struggling because the example code has a constant instance ID, and I can't create it dynamically. I'm really frustrated and would appreciate any help. Thank you!

**Comment by SergiusTheBest** [comment]
Do you know the number of Loggers at compile time?

**Comment by yangxq5858** [comment]
I don't Know. 
My requirement is to instantiate a global log object based on the file name and path provided by the caller. The log object should generate log files with names corresponding to the file name, and each object should save its logs separately.

**Comment by yangxq5858** [comment]
The new version does not support dynamic instantiation of IDs. I followed the solution provided in your previous mention of Issue 178 and implemented it based on the corresponding version.

**Comment by SergiusTheBest** [comment]
Oh, I see. You need to use the branch `dynamic-instances`. I didn't merge it yet as I need to write a documentation for that new feature.
