### ISSUE TITLE
Roll log on application start

### ISSUE THREAD

**Issue by stiggy87** [SergiusTheBest/plog#259]
I'm using PLOG as a way to track user interactions in my application, so it's separate from the main log. What I would like is that if the program is closed/re-opened that the second log is rolled at start. Is there a way to do that, or would it be a custom FileAppender?

**Comment by SergiusTheBest** [comment]
Yes, there is a way. Call `rollLogFiles` from `RollingFileAppender` at the beginning:

```
plog::RollingFileAppender<plog::TxtFormatter> fileAppender("file.log", 1000000, 1); 
fileAppender.rollLogFiles();
```

Thus you'll have one log file written from the start every time a program is launched.

**Comment by stiggy87** [comment]
Great! This works perfectly for what I want, even if I set the maxFiles to another value.

Thanks!
