### ISSUE TITLE
Log a packed argument list 

### ISSUE THREAD

**Issue by daniel-merrick** [SergiusTheBest/plog#260]
Hi I'm trying to print a packed argument list inside a function using the PLOG_XXXX macros. 

I get the following error when using the code at the bottom. Can you provide any assistance to resolve this?

plog/include/plog/Log.h:42:45: error: expected primary-expression before 'if'
   42 | #   define IF_PLOG_(instanceId, severity)   if (!plog::get<instanceId>() || !plog::get<instanceId>()->checkSeverity(severity))

```
void log(auto... args)
{
    (PLOG_FATAL << args, ...);    
}

int main()
{
    log(34, "bla", 15, 22);
}
```

Thank you

**Comment by daniel-merrick** [comment]
Ah I resolved it using a lambda with the following code snipped,

  ```
    (
          [&] {
            // Do things in your "loop" lambda
            LOG_FATAL << args << std::endl;
          }(),
          ...);
```

**Comment by SergiusTheBest** [comment]
@daniel-merrick  Yes, as LOG_FATAL is a multi-statement macro it can't be used in fold expressions directly.
