### ISSUE TITLE
Debug version using printf style alway cause Debug Assertion Failed!

### ISSUE THREAD

**Issue by blazewater-gmail** [SergiusTheBest/plog#261]
os: windows 10
build env: visual studio 2019
build debug demo or other sample, add `PLOGD.printf("%d, %s\n", __LINE__, __FUNCTION__)`
cause debug assertion.

see attached picture.
![1](https://github.com/SergiusTheBest/plog/assets/78136175/2cfc3a72-3299-4aa2-a66d-1ba53b98a72f)

**Comment by SergiusTheBest** [comment]
Thanks for your report! I successfully reproduced the issue and will investigate it further.

**Comment by SergiusTheBest** [comment]
The fix is pushed to master. Also appropriate tests were added.
