### ISSUE TITLE
Static linking of library

### ISSUE THREAD

**Issue by Ry-Kode** [SergiusTheBest/plog#262]
Hi,

First of all a HUGE thank you for this great library! Nice work, very clever design.

I do have some issues to build and statically link it into my executable. (Building on Raspberry pi, Raspberry OS 32 bit)

When I follow your instructions on https://github.com/SergiusTheBest/plog/issues/167 it looks like the static library (".a")  is not build.

Also, I noticed the headers are in /usr/local/include/plog. I would like to keep the in library folder ("/home/pi/libs/plog" in my case).

Can you please assist? 
Thanks!!

**Comment by SergiusTheBest** [comment]
Hi!

The library is header only so there is no need in ".a" files. You need just ".h" files. So you can copy it, use as a git submodule, or `make DESTDIR=/yourpath install`.

**Comment by Ry-Kode** [comment]
Don't know how i could have missed that !

Thank you Sergius!
