### ISSUE TITLE
Release 1.1.10?

### ISSUE THREAD

**Issue by bebuch** [SergiusTheBest/plog#264]
Will there be a new release soon? We need the patches currently included in the trunk to be able to compile with MSVC in C++20 mode and are therefore eagerly awaiting it. 🤗

**Comment by SergiusTheBest** [comment]
Yes. Expect it this week.

**Comment by bebuch** [comment]
Great! Thanks a lot 😸

**Comment by Smurf-IV** [comment]
This should not be closed until it is actually done ??

**Comment by SergiusTheBest** [comment]
Yeap.

**Comment by bebuch** [comment]
@Smurf-IV I considered it just a short question, but of course we can keep it open until it's done ;-)

**Comment by SergiusTheBest** [comment]
Done.
