### ISSUE TITLE
IF_LOG_ macro in if/else leads to miss else branch

### ISSUE THREAD

**Issue by popstk** [SergiusTheBest/plog#27]
The code below expects to output 'false'.

```
#include "plog/Log.h"

int main()
{
	plog::init(plog::info, "test.txt");

	LOG_INFO << "start";

	if (false)
		LOG_INFO << "true";
	else
		LOG_INFO << "false";
		
	LOG_INFO << "end";
}
```

2016-09-23 10:27:44.875 INFO  [1820] [main@13] start
2016-09-23 10:27:44.876 INFO  [1820] [main@20] end

It seems that the IF_LOG_ macro which has 'if ' leads to miss else branch.

**Comment by SergiusTheBest** [comment]
Interesting finding, thanks.
