### ISSUE TITLE
Please add instruction how to run samples 

### ISSUE THREAD

**Issue by repl-shenoy-sukumaran** [SergiusTheBest/plog#277]
Can you please give some instruction how to run samples e.g. Demo? Sorry i am new to C++ cmake etc

i have cloned the repo and tried within folder `samples\Demo`

- `cmake -Bbuildme` success. buildme folder is generated
- `cmake --build buildme --config Release` - error C1083: Cannot open include file: 'plog/Log.h': No such file or directory [C:\Workspaces\plog\samples\Demo\buildme\Demo.vcxproj]

Do we need to copy the `include/plog` manually somewhere?

![image](https://github.com/SergiusTheBest/plog/assets/13564819/b3ea97ba-f821-4f37-9632-af684defe8bc)

**Comment by paule32** [comment]
Hi,
you don't need cmake. PLOG is logging comes with header only usage.
So, you only need to give the path to plog/include with the g++ Option -I
source code (test.cc):
```
// -----------------------------------------------------------------
// standard header stuff ...
// -----------------------------------------------------------------

# include <stdio.h>
# include <stdlib.h>        // for _countof
# include <string.h>        // for strcpy_s

// -----------------------------------------------------------------
// c++ header prototype's/signature's:
// -----------------------------------------------------------------
# include <iostream>        // std c++ signatures
# include <string>
# include <cstdlib>
# include <cstring>

// -----------------------------------------------------------------
// loggin specified header files ...
// -----------------------------------------------------------------
# include <plog/Log.h>
# include <plog/Initializers/RollingFileInitializer.h>

namespace plog;
namespace std;

int main(int argc, char **argv)
{
    // ----------------------------------
    // initialize logging stuff ...
    // ----------------------------------
    plog::init(plog::debug, "app.log");
    PLOGI << "start application";;

    return EXIT_SUCCESS;
}
```

console:
`g++ -O2 -std=c++20 -Wno-write-strings -I../plog/include -o test.exe test.cc -L. -lz`

**Comment by SergiusTheBest** [comment]
@repl-shenoy-sukumaran Oh, you need to run cmake from the root folder and not from the `samples\Demo`. It will build the samples by default.

**Comment by repl-shenoy-sukumaran** [comment]
Thank you :)
