### ISSUE TITLE
More parsimonius inclusion of system header files

### ISSUE THREAD

**Issue by krlmlr** [SergiusTheBest/plog#28]
Currently, including Log.h gives me lots of system header files, most only useful for file appenders or for obtaining the current thread ID. This is not always appropriate. Consider not including the file appenders and the code they require for operation by default, or making their inclusion conditional. Looks like this requires splitting Init.h and Utils.h, and somehow making the thread ID optional.

My scenario requires cross-platform compatibility, I have built an [R package](https://github.com/krlmlr/plogr) that serves only as container for your library. I don't need the file appenders, and splitting took me too long, but I'd be happy to incorporate upstream changes if the library builds on Windows (MinGW), OS X, and Linux.

Thanks for providing the library!

**Comment by SergiusTheBest** [comment]
I'm not familar with R. Aren't platform headers available there?

**Comment by krlmlr** [comment]
You're forcibly including `windows.h`, which may be unavailable or at least not needed by the modules that use your library. I think a header-only library should carefully consider what to include.

**Comment by SergiusTheBest** [comment]
The commit 716f2078d289ac11c3f086874337c3111e4f1eef removed `windows.h` dependency. Could you check whether it works for you now?

**Comment by krlmlr** [comment]
Thanks. I'm unlikely to update my copy any time soon, so I can't be of much help here.

By now I've made some custom adjustments to my copy of plog, would you like to back-port any of these changes?

- krlmlr/plogr@4f1463a8: global `PLOGR_ENABLE` switch
- krlmlr/plogr@616ec2d: don't detect space in demangled name for better template support
- krlmlr/plogr@a0925ede: change severity of existing logger
- krlmlr/plogr@fd83874b: textual severity name -> enum
