### ISSUE TITLE
No "Log.h" in the plog directory

### ISSUE THREAD

**Issue by badcppdev** [SergiusTheBest/plog#293]
I'm trying to include plog in a project, and when i try to include it i can't find the "Log.h" file to actually include it.

**Comment by SergiusTheBest** [comment]
It depends on what path did you add to the include search directories. I recommend to do as described in the docs: https://github.com/SergiusTheBest/plog?tab=readme-ov-file#step-1-adding-includes so the library will have its own directory "namespace" and will not clutter with other libraries or project headers, the include code will look this way:

```cpp
#include <plog/Log.h>
```

**Comment by badcppdev** [comment]
> It depends on what path did you add to the include search directories. I recommend to do as described in the docs: https://github.com/SergiusTheBest/plog?tab=readme-ov-file#step-1-adding-includes so the library will have its own directory "namespace" and will not clutter with other libraries or project headers, the include code will look this way:
> 
> ```c++
> #include <plog/Log.h>
> ```

Thank you a lot!! This worked but another problem arose, when i try to compile a project with plog in it it gives a preprocessor error in the "Log.h" file for the specific line "#include <plog/Logger.h>" with the error "No such file or directory". I don't exactly know what is causing this because "Logger.h" does exist. Any idea what could be causing this?

**Comment by badcppdev** [comment]
(accidentally closed, sorry)

**Comment by badcppdev** [comment]
Nevermind, my compiler search directory settings bugged out. Sorry for wasting your time!

**Comment by SergiusTheBest** [comment]
@badcppdev I'm glad you figured it out. Have fun!
