### ISSUE TITLE
Help with set time

### ISSUE THREAD

**Issue by RomanYakhnenko** [SergiusTheBest/plog#294]
Hi! Use library in ESP-IDF - not undastand how set normal time from rtc - always start from 1970 - and now found set time function

**Comment by SergiusTheBest** [comment]
Hi! 

When a microcontroller begins working it doesn't know what time is it now. So it starts with time 0 which is year 1970. If you want to have the actual time you have to set it somehow: sync time from the internet, set it manually, have a battery power to keep RTC running and not resetting to 0. It's up to you how to implement that. The logging library just takes the time reported by RTC.

**Comment by RomanYakhnenko** [comment]
ok, i need use only processor time. in my project i have only external time, whant to connect ecternal function to get time - but not see where i may connect. Thanks
