### ISSUE TITLE
Stream manipulators support

### ISSUE THREAD

**Issue by davalv** [SergiusTheBest/plog#31]
Hi,
you can find attached my proposal to add stream manipulators support to plog.

[plog.zip](https://github.com/SergiusTheBest/plog/files/558586/plog.zip)

I have tried with the following manipulators and it works: std::dec, std::hex, std::oct, std::endl, std::left, std::setfill, std::setprecision, std::setw.

Can you review and include it in the next version of plog?

**Comment by SergiusTheBest** [comment]
Hi!

Could you provide a sample code? Because manipulators work for me without any changes:
```
LOGV << std::hex << 255;
```

**Comment by davalv** [comment]
Hi,
probably this issue is due to MS Visual Studio 2015 environment. Can you test with this IDE?

**Comment by SergiusTheBest** [comment]
Indeed, `std::endl` doesn't work. However `std::hex` works. Thanks.
