### ISSUE TITLE
Visual Studio or QT console

### ISSUE THREAD

**Issue by purell** [SergiusTheBest/plog#33]
Hi,

May I suggest to add this
```
#if defined(_DEBUG) && defined(_WIN32)
    OutputDebugString( ...)
#endif
```

to the ColorConsoleAppender for allowing outputting text in the VS or QT console ? Of course we will loose coloring but it is more convenient when debugging.

**Comment by SergiusTheBest** [comment]
Hi!

I thinks it will be more correct to add a new type of Appender that logs to the debug output.
