### ISSUE TITLE
Issue in Qt callbacks

### ISSUE THREAD

**Issue by d000x** [SergiusTheBest/plog#35]
Hello,

First of all, thanks for this pretty useful and easy-to-use lib. :)

I'm having an issue using it with Qt, the calls to LOG_DEBUG within a Qt callback (and subsequent calls) are not written in my output file.

I wonder if this is due to threads (possibly) created by Qt to manage its callbacks.

Is there something specific to do in order to use the logger in these callbacks ? Am I missing something ?

Thank you,

d!

**Comment by SergiusTheBest** [comment]
Hi there,

There should be nothing specific about Qt callbacks. Could you post some code?

**Comment by d000x** [comment]
Sure : 
In .h
`class MyClass : public QWidget {
...
    void showEvent(QShowEvent *event) Q_DECL_OVERRIDE;
...
}`

In .cpp
`
void CameraViewPage::showEvent(QShowEvent *)
{
    LOG_DEBUG << "In Method";
...
}`

Obviously, the logger is initialized before that and many messages are printed in my output file so I know it is working outside of this callback.
Nevertheless the message "In Method" cannot be found in my output file.
By the way, I made sure I actually execute code in this method by displaying a messagebox ;)
The same issue seems to occur for every callbacks.

Tell me if you need more information.

d!

**Comment by d000x** [comment]
Nevermind !! Mea Maxima Culpa !! There was an hidden setMaxSeverity(plog::info); in my code....

Everything is working fine !

**Comment by SergiusTheBest** [comment]
Ah, good.
