### ISSUE TITLE
Signed unsigned assignment warning

### ISSUE THREAD

**Issue by LiveToFly** [SergiusTheBest/plog#40]
RollingFileAppender.h
Line 76 should have explicit type casting to avoid warnings on platforms like osX
m_fileSize = **(size_t)**m_file.open(fileName.c_str());

**Comment by SergiusTheBest** [comment]
Good point. How did you find it?

**Comment by LiveToFly** [comment]
I have it included in my code and use it for writing logs.
It spits a warning every time file, it is included in, compiles.

Serge Z.

**Comment by SergiusTheBest** [comment]
Oh, I've found it. `-Wconversion` in Clang 3.5+.

**Comment by LiveToFly** [comment]
Will you fix it:-)
Thanks

Serge Z.

**Comment by SergiusTheBest** [comment]
Of course. Just want to make sure that CI will detect such warning in future.

**Comment by LiveToFly** [comment]
Here is the exact warning from xCode build:
plog/Appenders/RollingFileAppender.h:76:26: Implicit conversion loses
integer precision: 'off_t' (aka 'long long') to 'size_t' (aka 'unsigned
long’)
just in case


Serge Z.
