### ISSUE TITLE
error on ConsoleAppender

### ISSUE THREAD

**Issue by petrus2069** [SergiusTheBest/plog#42]
I'm trying to use multi appender sample

static plog::RollingFileAppender<plog::CsvFormatter> fileAppender("MultiAppender.csv", 8000, 3); // Create the 1st appender.
static plog::ConsoleAppender<plog::TxtFormatter> consoleAppender; // Create the 2nd appender.
plog::init(plog::debug, &fileAppender).addAppender(&consoleAppender); // Initialize the logger with the both appenders.

but I get the error:
error: ‘ConsoleAppender’ in namespace ‘plog’ does not name a template type

I'm using gcc  4.9.4 on ubuntu 14.04 wiht Eclipse 3.8

**Comment by SergiusTheBest** [comment]
Hi!

Do you have `#include <plog/Appenders/ConsoleAppender.h>`?

**Comment by petrus2069** [comment]
That's right. I was missing that include

Thanks you

**Comment by SergiusTheBest** [comment]
No problem!
