### ISSUE TITLE
Missing header includes

### ISSUE THREAD

**Issue by allannk** [SergiusTheBest/plog#47]
When installing to /usr/include/plog on a linux box, `RollingFileAppender.h` seems to be missing 

    #include <plog/Appenders/IAppender.h>

and `IAppender.h`

    #include <plog/Record.h>

**Comment by SergiusTheBest** [comment]
Yes, the idea was to always include `Log.h` first:
```cpp
#include <plog/Log.h>
#include <plog/Appenders/RollingFileAppender.h>
```
But it looks like it's better to have self-sufficient headers.
