### ISSUE TITLE
EventLogAppender not working

### ISSUE THREAD

**Issue by ThirtySomething** [SergiusTheBest/plog#48]
Hi Sergey,

looks that the EventLogAppender is no longer working. I was not able to create event log entries. More worse is that the chaining of RollingFileAppender and EventLogAppender will result in nothing logged at all.

I'm using the following code for init:
```
std::string ProgName = _T("PlogTest");
CString LogFileName;
LogFileName.Format(_T("C:\\Temp\\%s.log"), ProgName.c_str());
static plog::RollingFileAppender<plog::TxtFormatter> LogFile(LogFileName, 1000000, 5);
std::wstring EventLog = std::wstring(ProgName.begin(), ProgName.end());
if (false == plog::EventLogAppenderRegistry::exists(EventLog.c_str()))
{
	plog::EventLogAppenderRegistry::add(EventLog.c_str());
}
static plog::EventLogAppender<plog::TxtFormatter> LogEvent(EventLog.c_str());
plog::init(plog::verbose, &LogFile).addAppender(&LogEvent);

```

I've tested both, with and without admin privileges and got the same result. The OS user has local admin privileges.

The project specific settings are:
- Platformtoolset Visual Studio 2010 (v100)
- Usage of MFC in a common used DLL
- Using Multibyte character set
- No optimizing

The OS is Win7 Pro 64 and I'm working with Visual Studio 2013.

**Comment by SergiusTheBest** [comment]
Hi there,

It works for me:
![log](https://cloud.githubusercontent.com/assets/4660722/24813572/2bead790-1bd7-11e7-95eb-5a232bb0cf31.png)
and c:\temp\PlogTest.log:
```
2017-04-07 21:11:49.398 DEBUG [11748] [main@27] test
2017-04-07 21:12:34.695 DEBUG [13484] [main@27] test
```
However I used ATL instead of MFC:
```cpp
#include <plog/Log.h>
#include <plog/Appenders/EventLogAppender.h>
#include <atlstr.h>

using namespace std;

int main()
{
    std::string ProgName = _T("PlogTest");
    CString LogFileName;
    LogFileName.Format(_T("C:\\Temp\\%s.log"), ProgName.c_str());
    static plog::RollingFileAppender<plog::TxtFormatter> LogFile(LogFileName, 1000000, 5);
    std::wstring EventLog = std::wstring(ProgName.begin(), ProgName.end());
    if (false == plog::EventLogAppenderRegistry::exists(EventLog.c_str()))
    {
        plog::EventLogAppenderRegistry::add(EventLog.c_str());
    }
    static plog::EventLogAppender<plog::TxtFormatter> LogEvent(EventLog.c_str());
    plog::init(plog::verbose, &LogFile).addAppender(&LogEvent);

    LOGD << "test";

    return 0;
}
```

**Comment by SergiusTheBest** [comment]
Any news?

**Comment by ThirtySomething** [comment]
Hi Sergey,

sorry for the late answer. You can find a test project [here ](https://1drv.ms/u/s!ApZ1wFdKcPCGgrI36mXY-7j7t3IB-w) which is using MFC. Keep in mind that this is for Visual Studio 2010. I discovered that the kind of logging is important. After changing from LOGI to LOGE, the logfile was written. But I was not successful to get a entry in the event log. 

Regards

ThirtySomething

**Comment by SergiusTheBest** [comment]
Your sample worked for me. I changed:
```cpp
// Init plog
plog::init(plog::verbose, &PlogLogFile).addAppender(&PlogLogEvent);
//plog::init(plog::verbose, &PlogLogEvent);
```
and got log messages in the eventlog and a file.

**Comment by ThirtySomething** [comment]
Woha, that's really strange. So I assume that there is something very special in my environment (OS Win7Prof 64 and/or VS 2010) that will prevent the correct working. But as long as I get a log file, everything is okay. I apologize for the inconvenice and thank you  for your support.

**Comment by SergiusTheBest** [comment]
No problem.
