### ISSUE TITLE
Log flushed to disk only at end of my program

### ISSUE THREAD

**Issue by nilopaim** [SergiusTheBest/plog#49]
Hi,

I call `plog::init(plog::verbose, "log.txt")` at the beggining of my program. During execution, I call `LOG_INFO`
several times. I want to monitoring the execution of my program by examining the log file (my program runs for a long time), but the log file is flushed to disk only at the end of my program.

How to force flushing at each logged message (I don't care about the performance)?

Thanks!

**Comment by SergiusTheBest** [comment]
Hi there,

What is your compiler and OS?

**Comment by nilopaim** [comment]
Windows 10, 64 bits and Visual Studio 2015 Pro.

**Comment by SergiusTheBest** [comment]
Then everything should be fine. How do you check the log file for updates?

**Comment by nilopaim** [comment]
Any text editor... But I will try BareTail.

**Comment by nilopaim** [comment]
BareTail works...

But some log messsages are written out of order. My program has no threads involved...

**Comment by nilopaim** [comment]
Please, forget last comment. It was my fault.

I am closing the issue.

Congratulations for your software. Really nice piece of work.

And many thanks for ypur prompt response!

Greetings from Brazil!
Nilo

**Comment by SergiusTheBest** [comment]
Usually text editors do not reload changes automatically. So try manual refresh.

**Comment by SergiusTheBest** [comment]
No problem, have a nice day!
