### ISSUE TITLE
Problem multi Instance with int value

### ISSUE THREAD

**Issue by fabri8bit** [SergiusTheBest/plog#5]
this is not possible:

http://pastebin.com/paiK299R

....

LOG

help me.

**Comment by SergiusTheBest** [comment]
Yes, you cannot change a template parameter in a loop - it must be a compile-time constant. Why do you want that?

**Comment by fabri8bit** [comment]
my program is multithreading. N thread = N log file different. I execute new thread into for cicle.

**Comment by SergiusTheBest** [comment]
Why do you need a separate log instance per thread?

**Comment by fabri8bit** [comment]
http://pastebin.com/Dkd449Hg

**Comment by SergiusTheBest** [comment]
Here are some options:
1. Use `csv` log format, filter the resulting log file by thread id (This is my favorite method).
2. Write your own appender that produces per-thread log files.
3. Unroll your loop and make the work function templated:
```cpp
template<class int N>
void example(int x, int y)
{
    ....
    plog::init<N>(plog::debug, ...);
    LOGI_(N) << "CURRENT FILE  : " << file_tmp;  
    ...
}

int main()
{
    ...
    futures.push_back(async(std::launch::async, example<1>, 5,6));
    futures.push_back(async(std::launch::async, example<2>, 5,6));
    futures.push_back(async(std::launch::async, example<3>, 5,6));
    futures.push_back(async(std::launch::async, example<4>, 5,6));
    ...
}
```
