### ISSUE TITLE
It crashed in iphone.

### ISSUE THREAD

**Issue by PraflyGod** [SergiusTheBest/plog#51]
![7a493b44-5e2f-443b-9fd3-25e51270403e](https://cloud.githubusercontent.com/assets/13954697/25835011/26bbf322-34ae-11e7-95ab-227b2046fcc8.png)

It seeams that something wrong with getfunc().

**Comment by SergiusTheBest** [comment]
Which version of plog are you using?

**Comment by SergiusTheBest** [comment]
There was a similar issue and it's fixed in 1.0.2.

**Comment by PraflyGod** [comment]
shoud be commit commit 9aea30d7b9bb74b6ff775a3c38dc4417073fd93b

**Comment by SergiusTheBest** [comment]
That's strange. Could you make a demo project and attach it here?

**Comment by PraflyGod** [comment]
Just common project. You can build a .so share library using plog, then use it in app project。

**Comment by SergiusTheBest** [comment]
How to link iOS app with dylib?

**Comment by SergiusTheBest** [comment]
Closing as obsolete.
