### ISSUE TITLE
Log not flushed

### ISSUE THREAD

**Issue by davalv** [SergiusTheBest/plog#53]
I seen that "_util::File_" class not flushes text.
I see that pLog uses "_open_" and "_close_" functions that are not POSIX compliant and, at least in Linux, the "_close_" function only close file descriptor without flushing text: so the output maybe truncated.

Is it better to use the "_fopen_" and "_fclose_" functions?

Can you fix this issue? It is a big problem for me.

Kind regards

**Comment by SergiusTheBest** [comment]
My notes:
1. `open/close` are from POSIX, `fopen/fclose` are from C-runtime. So both are very portable.
2. `open/close` doesn't require any flushing as buffering is performed by kernel (in contrast to `fopen/fclose`). So `open/close` is better and output truncation is not possible.

**Comment by davalv** [comment]
Sorry, I realized I was confused. :-)
I was also mistaken because the file system of my server was full and plog sometimes was unable to write. 
It would not be the case to write errors to `stderr` in all functions of `Util.h`?

**Comment by SergiusTheBest** [comment]
> It would not be the case to write errors to stderr in all functions of Util.h?
I don't want to overcomplicate things.
