### ISSUE TITLE
-liconv needed for compilation on Mac OS X 10.10

### ISSUE THREAD

**Issue by perwin** [SergiusTheBest/plog#55]
Just a minor suggestion: it might be useful to note somewhere that in order to get compilation on Mac OS X 10.10 (and possibly later, though I haven't checked) to work, you need to explicitly link to the iconv library ("-liconv").

**Comment by SergiusTheBest** [comment]
Good point. Thank you.

**Comment by SergiusTheBest** [comment]
Note that you don't need `iconv` now unless you want to support wchar_t.
