### ISSUE TITLE
const char * : unhandled exception in lib <string>

### ISSUE THREAD

**Issue by pcorbineau** [SergiusTheBest/plog#57]
When i use plog in my main i have no problems,

but i wanna use it on other function but i got unhandled exception in visual studio.

my call was something like that : 

`LOGI << "Some text here";`

I correct first the problem by adding always std::string constructor in my debug text but it was really boring

`LOGI << std::string("Some text here");`

Finally I correct the problem by adding this in record.h

```
		Record& operator<<(const const char* data)
		{
			using namespace plog::detail;

			m_message << std::string(data);
			return *this;
		}
```
Do you have any idea what is wrong ?

**Comment by SergiusTheBest** [comment]
That's strange. Could you provide the full sources that demonstrate the problem?

**Comment by pcorbineau** [comment]
Sorry i can't!
This is a private project

Now i think it's not really your project the problem but a conflict between include in the project.


I will try with a blank project to simulate the problem.

**Comment by SergiusTheBest** [comment]
Yes, I meant the blank project (not the real one).

**Comment by SergiusTheBest** [comment]
By the way, what kind of exception do you see?

**Comment by pcorbineau** [comment]
Ok i test in a blank app and i try to simulate my problem by calling "LOG << " from a class, from another cpp file like c code, from static functions or other things like that. I don't have any problem. I am investigate on my main project.

So i think it can be due to : 

- conflict with another library include

- conflict with a personal define containing a LOG symbol but the compiler dont see it

- a compiling problem due to inline optimization

I am investigating and come back with you if i find something interesting

My exceptions are : 

- `LOGI << "Some text"`
error in string library : 

> Exception thrown at 0x009813E5 in MyApp.exe: 0xC0000005: Access violation reading location 0xCCCCCCD0.

error line 177 lib string in VisualStudioPath\VC\include\string

- `LOGI << L"Some text"`
error in ostream library : 

> Exception thrown at 0x0020A60E in ShadowClient.exe: 0xC0000005: Access violation reading location 0xCCCCCCD0.

error line 871 lib ostream in VisualStudioPath\VC\include\ostream

Yesterday instead of 0xCCCCCCD0 i got 0xC0000004 address

**Comment by pcorbineau** [comment]
In : 

```
        inline void operator<<(util::nstringstream& stream, const char* data)
        {
            data = data ? data : "(null)";

#if defined(_WIN32) && defined(__BORLANDC__)
            stream << util::toWide(data);
#elif defined(_WIN32)
            std::operator<<(stream, util::toWide(data));
#else
            std::operator<<(stream, data);
#endif
```

How can i check if plog::init works?

my scenario : 
```
		plog::init(plog::debug, "test.txt");
		LOGI << "TEST";
```


It seems that `stream` is not initialize refering to visual studio exception thrown.

**Comment by SergiusTheBest** [comment]
Note that `0xcccccccc` means an uninitialized stack memory.

**Comment by SergiusTheBest** [comment]
Do you do anything unusual in your project: mixing different visual studio compilers, loading dlls in a hackish way, and so on?

**Comment by SergiusTheBest** [comment]
Are there any news?

**Comment by SergiusTheBest** [comment]
Did you resolve the issue?
