### ISSUE TITLE
Changing global locale in ConsoleAppender

### ISSUE THREAD

**Issue by SergeyKrivohatskiy** [SergiusTheBest/plog#58]
On windows ConsoleAppender constructor changes locale with `::setlocale(LC_ALL, "")`. That may cause troubles. https://github.com/SergiusTheBest/plog/blob/master/include/plog/Appenders/ConsoleAppender.h#L15
We are using PLOG in a dynamic library. It may be linked to a binary that may depend on locale settings (in our case it sets and expects "C" locale).

In case changing locale is required for PLOG library I believe it can be done locally using `imbue` http://en.cppreference.com/w/cpp/io/basic_ios/imbue.

**Comment by SergiusTheBest** [comment]
Good point, I'll take a look at it.
