### ISSUE TITLE
vcpkg?

### ISSUE THREAD

**Issue by dalebrubaker** [SergiusTheBest/plog#59]
Do you have any plans to add this to vcpkg?
I see some other loggers are available: https://blogs.msdn.microsoft.com/vcblog/2016/09/19/vcpkg-a-tool-to-acquire-and-build-c-open-source-libraries-on-windows/
But I like plog! :)

**Comment by SergiusTheBest** [comment]
Yes, I'm working on it. Thanks for raising the issue!

**Comment by alexkaratarakis** [comment]
Link: https://github.com/Microsoft/vcpkg/pull/1625

**Comment by dalebrubaker** [comment]
This works great now. Thank you!
