### ISSUE TITLE
record.h(101): error C2593: 'operator <<' is ambiguous

### ISSUE THREAD

**Issue by smsaleem** [SergiusTheBest/plog#60]
Hi,
I am using plog in an MFC dialog based Unicode project, in visual studio 2017.

I am getting the following error -

record.h(101): error C2593: 'operator <<' is ambiguous

Please help.

Regards,

**Comment by smsaleem** [comment]
The project Encoding is based upon Unicode / Wide Character 

The issue is solved with the following steps

In Record.h file from line number 30

#if PLOG_ENABLE_WCHAR_INPUT
        inline void operator<<(util::nstringstream& stream, const wchar_t* data)
        {
            data = data ? data : L"(null)";

#ifdef _WIN32
            std::operator<<(stream, data);
#else
            std::operator<<(stream, util::toNarrow(data));
#endif
        }

        inline void operator<<(util::nstringstream& stream, const std::wstring& data)
        {
            plog::detail::operator<<(stream, data.c_str());
        }
#endif

The code has been modified / commented 

#if PLOG_ENABLE_WCHAR_INPUT
//        inline void operator<<(util::nstringstream& stream, const wchar_t* data)
//        {
//            data = data ? data : L"(null)";
//
//#ifdef _WIN32
//            std::operator<<(stream, data);
//#else
//            std::operator<<(stream, util::toNarrow(data));
//#endif
//        }

        inline void operator<<(util::nstringstream& stream, const std::wstring& data)
        {
            plog::detail::operator<<(stream, data.c_str());
        }
#endif

The issue stand resolved now.

Thanks for the great library.

Regards,

**Comment by SergiusTheBest** [comment]
By the way you can `#define PLOG_ENABLE_WCHAR_INPUT 0` prior to including `plog.h` or in the project settings so you don't need to alter the source code.

**Comment by smsaleem** [comment]
It worked like a charm.

Thanks & regards,
________________________________
