### ISSUE TITLE
can I Change log filename at runtime?

### ISSUE THREAD

**Issue by xiaominnn** [SergiusTheBest/plog#62]
plog can change severity at runtime.but I want to konw if I can change log filename at runtime?how can I do it?

**Comment by SergiusTheBest** [comment]
No, it cannot be done out of the box. If you need such functionality you have to write your own `FileAppender` (it's not very hard).

**Comment by xiaominnn** [comment]
When I use Appender,log can also write into the file before and the file that change the filename.
I want to log can roll through date.But,plog can just be rolling through maxFileSize and maxFiles.
So I want to implement it through other method .for example ,change the log file name.Can plog implement that function?Thank your answer.

**Comment by SergiusTheBest** [comment]
Yes, such functionality is planned but ETA is not specified. You can take a look at #52. That implementation is not perfect but should help you.

**Comment by jediMunees** [comment]
Hi @xiaominnn ,
I need this case too. I have created custom appender at https://github.com/jediMunees/plog/commit/bfd5157d885577443931576d930189f039ddaaf0 . Please look into it. 

Hi @SergiusTheBest , 
If you get sometime, please have a look at this commit.

**Comment by SergiusTheBest** [comment]
A new method `setFileName` is added to `RollingFileAppender`, so now a log file name can be changed at runtime. Take a look at [SetFileName](https://github.com/SergiusTheBest/plog/blob/master/samples/SetFileName/Main.cpp) sample.
