### ISSUE TITLE
Error with String^

### ISSUE THREAD

**Issue by tom6868** [SergiusTheBest/plog#63]
Hello,

First, i want to thank you for this log system.
Your addon is very cool and i wouldn't drop it to another one.
But i got an error which forbids me to continue.
I can't use String in any project or i get an error.
The compile debug says that i need to put an "^" after String.

It is working fine. But, if i want to "log" a string^ variable nammed "port" with "LOGI", i get an error.
I also tried "&port" but in the log i got an var adress (Pointer) instead of variable.

I'm Visual Studio 2017 and C++ language.

My Code : https://pastebin.com/P1cRMR8S
The error : https://pastebin.com/CGviZRbe

Thanks really for service,
Tom

**Comment by SergiusTheBest** [comment]
Hi Tom,

I'm glad you liked plog. I added support for `System::String^`. Please, try it and tell me wether it works for you.

**Comment by tom6868** [comment]
Thanks really for your attention.
I updated the record but got another error.
Here the error : https://pastebin.com/Pz608G77

**Comment by SergiusTheBest** [comment]
That's strange. Could you build a "Demo" sample as managed C++ project?

**Comment by tom6868** [comment]
There is the code : https://pastebin.com/uYs9uCgz and the error : https://pastebin.com/eWjSwzb4

**Comment by SergiusTheBest** [comment]
Works with no issues. Visual Studio 2015 and 2017. Could you post the whole solution? Maybe there is something wrong in project settings or stdafx.

**Comment by tom6868** [comment]
Okay, i created another project and removed the "Precompiled Headers" option. It is now working fine. Thank you very much !

**Comment by SergiusTheBest** [comment]
Ok.
