### ISSUE TITLE
try test the demo with google test and Visual Leak Detector

### ISSUE THREAD

**Issue by yudiannlu** [SergiusTheBest/plog#64]
hi
I try test your sample - demo with Google test and vld for visual studio 2015.

I have memory leak issue need your help. If you could help me to look this issue. I could send you my simple google plog test project code to you.

Thanks

**Comment by SergiusTheBest** [comment]
Hi!

Post it here.

**Comment by yudiannlu** [comment]
Sorry, I don't know how to post whole project, so attach a zip.
I try to find a simple log in C++.

[plogGTest.zip](https://github.com/SergiusTheBest/plog/files/1235167/plogGTest.zip)

**Comment by SergiusTheBest** [comment]
`plog::init` is designed for one time initialization and live for the whole app lifetime. In your case (unit tests) you need to create and delete everything, so you need to replace `plog::init` wth manual logger and appender initialization:
```cpp
plog::RollingFileAppender<plog::TxtFormatter> appender("Hello.txt");
plog::Logger<PLOG_DEFAULT_INSTANCE> logger(plog::verbose);
logger.addAppender(&appender);
```
Thus the logger will have a local lifetime and will be recreated for each test case.

**Comment by yudiannlu** [comment]
How to use plog like the printf(",,,,,", xx)?

**Comment by SergiusTheBest** [comment]
You need to use plog with https://github.com/fmtlib/fmt :
```cpp
LOGI << fmt::sprintf("%d %s", 10, "test");
LOGI << fmt::format("{0} {1}", 12, "test");
```

**Comment by SergiusTheBest** [comment]
I guess the issue can be closed?
