### ISSUE TITLE
Support operator<<(std::ostream& os, ...) custom operators on Windows

### ISSUE THREAD

**Issue by DesktopMan** [SergiusTheBest/plog#66]
Currently it's difficult to use the same code across platforms because Plog expects operator<< to use std::wostream on Windows, while on Linux (and OSX?) you need to use std::ostream. Thus code that builds on Linux fails to build on Windows and the other way around.

If there are other ways to have common operators across platforms I'd love to know.

**Comment by SergiusTheBest** [comment]
Could you provide an example of a problem code?

**Comment by SergiusTheBest** [comment]
Do you mean a custom operator<< ?

**Comment by DesktopMan** [comment]
yes, when I provide a custom operator<<.

```
std::ostream& operator<<(std::ostream& os, const Customer& customer)
{
    os << customer.id << " | " << customer.firstName << " | " << customer.lastName;
    return os;
}
```
I'm not seeing how I can make this cross platform compatible currently.

**Comment by SergiusTheBest** [comment]
I see. I'll take a look what can be done.

**Comment by SergiusTheBest** [comment]
Please, try a version from the `ostream-operator-support` branch and tell me how it works for you.

**Comment by SergiusTheBest** [comment]
Now plog should use any of `std::ostream& operator<<` or `std::wostream& operator<<`.

**Comment by DesktopMan** [comment]
I've tested the branch on Windows with MinGW64 6.1.0 and everything works as expected with my existing project using the file logger. Also tested on Linux.

**Comment by SergiusTheBest** [comment]
Excellent.

**Comment by SergiusTheBest** [comment]
Merged to master.
