### ISSUE TITLE
Could not build plog for Android armeabi-v7a

### ISSUE THREAD

**Issue by gamapat** [SergiusTheBest/plog#68]
Hi,
I've troubles with building Plog for Android armeabi-v7a since this commit https://github.com/SergiusTheBest/plog/commit/e65b38f6b11444718517590cf4605784fc55ef0b.
Main reason is fileno symbol is actually the macros on this platform, and this line
```
::fileno(stdout)
```
converts to this
```
::stdout->_file
```
which makes compiler generate error report.
I've tried to remove :: before fileno and it works just fine for me.

Can you fix it?

**Comment by SergiusTheBest** [comment]
Done.
