### ISSUE TITLE
init() function maxFileSize don't work when maxFiles is 1

### ISSUE THREAD

**Issue by SCNUPeiFeng** [SergiusTheBest/plog#70]
My code is: plog::init(plog::debug, "mylog.log", 1024 * 1024 * 1, 1);
When maxFiles is 1, maxFileSize don't work. The file size of mylog.log more than 1 MB, but  it's ok when maxFiles is greater than 1.

**Comment by purell** [comment]
Is this issue has been resolve ? I have the same problem here.

```c++
static plog::RollingFileAppender<plog::TxtFormatter> fileAppender(logFilePath, 1048576, 1);
```

I'm getting a file 168Mo

**Comment by SergiusTheBest** [comment]
Thank you for reminding me! The fix is pushed to the master.
