### ISSUE TITLE
Max log level not working on appender

### ISSUE THREAD

**Issue by lampcord** [SergiusTheBest/plog#71]
I'm having an issue with having a logger's different max level for an appender as opposed to the log file. I tried this:

```
static plog::ColorConsoleAppender<plog::TxtFormatter> consoleAppender;
plog::init(plog::debug, "log.txt");
plog::init(plog::info, &consoleAppender);
```

The idea was that debug and below would go to log.txt while only info and below would go to the console. However, it seemed that the log level I chose in the second call to plog::init didn't have any effect. Either way, I would get the same log messages in both places. Is this by design? If so, I'm not clear on what value the plog::info parameter serves in the second call to plog::init.

**Comment by SergiusTheBest** [comment]
`plog::init` is a one-shot call (so it does nothing on the second call). You can accomplish the task with the following:
```cpp
// init console logger
enum { kConsole = 1 };
static plog::ColorConsoleAppender<plog::TxtFormatter> consoleAppender;
plog::init<kConsole>(plog::info, &consoleAppender);

// init default logger, attach console logger to it
plog::init(plog::debug, "log.txt").addAppender(plog::get<kConsole>());
```
