### ISSUE TITLE
Different severity levels for chained loggers

### ISSUE THREAD

**Issue by ilammy** [SergiusTheBest/plog#72]
Hi,

I have an issue that is similar to #9, but slightly different. I would like to have several loggers for multiple subsystems with different severity levels, and a default catch-all logger. All logs should we be written into a single log file.

That is, the following code:

```
LOG_INFO      << "line 1";
LOG_DEBUG     << "line 2";
LOG_INFO_(1)  << "line 3";
LOG_DEBUG_(1) << "line 4";
LOG_INFO_(2)  << "line 5";
LOG_DEBUG_(2) << "line 6";
```

with the following severity levels

* 0 — info
* 1 — debug
* 2 — warning

should produce a log file with lines

```
line 1
line 3
line 4
```

The idea is to be able to enable debug-level logs for each subsystem separately, but still log everything in a consistent manner into a single sink.

The documentation suggests that chained loggers should be used:

```
plog::init<0>(plog::info, "/var/log/my.log");
plog::init<1>(plog::debug, plog::get<0>());
plog::init<2>(plog::warning, plog::get<0>());
```

However, this produces the following log output:

```
line 1
line 3
```

The log entries are first filtered by chained loggers according to their respective severity levels, but then they are filtered again by the root logger. Thus the debug logs from 1 are not visible.

I guess it could be worked around by doing something like this:

```
plog::init<0>(plog::none, "/var/log/my.log");
plog::init<1>(plog::info, plog::get<0>());
plog::init<2>(plog::debug, plog::get<0>());
plog::init<3>(plog::warning, plog::get<0>());
```

and using logger 1 as the default one, loggers 2 and 3 for subsystems, and never using the logger 0 explicitly. However, it's so nice to simply write `LOG_DEBUG` instead of `LOG_DEBUG_(Default)` throughout the code by default :)

Is there some non-obvious way to get this 'defaulting' behavior with chained loggers, or the suggested way with explicit default logger should be used?

**Comment by ilammy** [comment]
Oh, it's just me being dumb 🤦‍

The same appender can be reused and specified for the subsystem loggers:

```
static plog::RollingFileAppender<plog::TxtFormatter> appender("/var/log/my.log");

plog::init<0>(plog::info, &appender);
plog::init<1>(plog::debug, &appender);
plog::init<2>(plog::warning, &appender);
```

**Comment by SergiusTheBest** [comment]
Also you can rewrite your previous sample:
```cpp
plog::init<1000>(plog::none, "/var/log/my.log");
plog::init<0>(plog::info, plog::get<1000>());
plog::init<1>(plog::debug, plog::get<1000>());
plog::init<2>(plog::warning, plog::get<1000>());
```
so the default log stays `0` and the sink becomes `1000`.
