### ISSUE TITLE
Compile error on msvc2017 x64

### ISSUE THREAD

**Issue by ahoarau** [SergiusTheBest/plog#73]
I'm having an issue with the visual studio compiler 2017 (x64) : 
```
plog-1.1.3\include\plog/Util.h(363): error C2248: 'plog::util::Mutex::lock': cannot access private member declared in class 'plog::util:
:Mutex'
plog-1.1.3\include\plog/Util.h(368): error C2248: 'plog::util::Mutex::unlock': cannot access private member declared in class 'plog::uti
l::Mutex'
```

Is it possible it can't read the ``friend class MutexLock` ?

**Comment by ahoarau** [comment]
Temporary ugly fix : 
``` 
331 #ifndef _WIN32
332         private:
333 #endif
```

**Comment by SergiusTheBest** [comment]
Let me check that.

**Comment by SergiusTheBest** [comment]
I couldn't reproduce it. Everything is fine on my MVS 2017. Could you provide a demo sample?

**Comment by SergiusTheBest** [comment]
Any news?

**Comment by ahoarau** [comment]
Sorry I didn't respond earlier. Nope I cannot reproduce either with a simple test program. I'm closing for now.
