### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [SergiusTheBest/plog#75]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by SergiusTheBest** [comment]
Hi!

Yes, I know about Conan. But I had connection issues with their servers in the past (as they were moving to bintray). I hope they are ok now. 

Thanks for the suggestion, I'll take a look again.

**Comment by rainx** [comment]
any updates? I am using conan in my project and wanna use it to add plog to my project .. hope it will be done soon ..  :)

**Comment by variar** [comment]
This conan recipe can be used to build simple package without tests.

```python
from conans import ConanFile
class PlogConan(ConanFile):
    name = "plog"
    version = "1.1.3"
    # No settings/options are necessary, this is header only
    no_copy_source = True

    def source(self):
        self.run("git clone https://github.com/SergiusTheBest/plog.git")
        self.run("cd plog && git checkout tags/1.1.3")

    def package(self):
        self.copy("plog/include/*.h")

    def package_id(self):
        self.info.header_only()
```

@rainx could you try the resulting  [package](https://github.com/SergiusTheBest/plog/files/1567496/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9.zip)?

**Comment by ZaMaZaN4iK** [comment]
What about contributing your recipe to conan-center?

**Comment by variar** [comment]
I've never worked with conan before. I think that recipe should be provided by @SergiusTheBest  as the library author. If that is not the case I can try to contribute my recipe.

I've set up personal conan playground on Bintray to test if it works
```
 conan remote add variar-conan-test https://api.bintray.com/conan/variar/conan-test
```

**Comment by ZaMaZaN4iK** [comment]
Ok, thank you. Also i suggest you visit cpplang.slack.com, #conan and #bincrafters channels

If you will get workable conan recipe, please contribute it to conan-center.

**Comment by rainx** [comment]
@variar thx .
Just test your package from bintray.  I an now using vs2015 as a target .. and generate vs props files, I found your package is not add incluce path on it.. 

attached
[conanfile.txt](https://github.com/SergiusTheBest/plog/files/1570361/conanfile.txt)
 my props file. 
[conanbuildinfo.props.txt](https://github.com/SergiusTheBest/plog/files/1570364/conanbuildinfo.props.txt)

[conanbuildinfo.txt](https://github.com/SergiusTheBest/plog/files/1570369/conanbuildinfo.txt)

**Comment by rainx** [comment]
@variar  changing include path may fix this ,and it works for me

```python
from conans import ConanFile
class PlogConan(ConanFile):
    name = "plog"
    version = "1.1.3"
    # No settings/options are necessary, this is header only
    no_copy_source = True

    def source(self):
        self.run("git clone https://github.com/SergiusTheBest/plog.git")
        self.run("cd plog && git checkout tags/1.1.3")

    def package(self):
        self.copy("*.h", src="plog/include", dst="include")   #xxx: changes here

    def package_id(self):
        self.info.header_only()
```

**Comment by variar** [comment]
Thanks. I've updated package on bintray with @rainx changes

**Comment by macdew** [comment]
plog is now available on conan-center with an official recipe as per https://github.com/conan-io/conan-center-index/tree/master/recipes/plog/all

I think this issue can be closed now?   (I've just started to use that exact conan recipe and can confirm it works fine)

**Comment by SergiusTheBest** [comment]
@macdew Yes. The recipe is good. Thanks!
