### ISSUE TITLE
Possible to use ColorConsoleAppender only on certain types of messages?

### ISSUE THREAD

**Issue by PCieslewski** [SergiusTheBest/plog#78]
Hello! I was wondering if it was possible to use ColorConsoleAppender only on certain types of messages?

For example, I want to log debug and above to file, but I want error messages and above to be displayed in console.

Sorry if this is obvious from the documentation!

Thank you for your time!

**Comment by variar** [comment]
Looks like this should be possible by chaining two loggers with different severity settings and appenders. Something like this

```c++
#include "plog/Log.h" 
#include "plog/Appenders/ColorConsoleAppender.h"
#include "plog/Appenders/RollingFileAppender.h"

int main()
{
    plog::RollingFileAppender<plog::TxtFormatter> fileAppender("debug.log", 8000, 3);
    plog::init(plog::debug, &fileAppender);

    plog::ColorConsoleAppender<plog::TxtFormatter> consoleAppender;
    plog::init<1>(plog::error, &consoleAppender);

    plog::get()->addAppender(plog::get<1>());

    LOG_DEBUG << "Debug message";
    LOG_ERROR << "Error message";
}
```

**Comment by SergiusTheBest** [comment]
Thank you, @variar. You are absolutely correct.

@PCieslewski The message flow will be:
```
msg --> default logger --> fileAppender
                      \
                       --> logger<kConsole> ---> consoleAppender
```

**Comment by PCieslewski** [comment]
Thank you kindly!
