### ISSUE TITLE
gcc warning when compiling with plog

### ISSUE THREAD

**Issue by eldadr** [SergiusTheBest/plog#79]
When compiling our C++ software with plog, we have the following gcc warning (multiple times):

```
../plog/include/plog/Record.h:99:11: warning: ‘class plog::Record’ has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]
     class Record
           ^
```

gcc version: `gcc 5.4.0-6ubuntu1`
gcc flags: `-std=c++03 -pg -O0 -g -Wall -Wextra -pthread`
plog version: `1.1.3`

**Comment by SergiusTheBest** [comment]
It's strange bacause `-Wall` doesn't include `-Wnon-virtual-dtor`.  Anyway I pushed the fix.

**Comment by eldadr** [comment]
Thanks.
Apparently the `-Wnon-virtual-dtor` flag was added to the gcc command under the hood by the build system.
