### ISSUE TITLE
How to configure plog to write each message on its own line on Windows?

### ISSUE THREAD

**Issue by grandtiger** [SergiusTheBest/plog#81]
I just tried the example and found that the log messages are all on one line.

I believe it's the difference between Linux(LF) and Windows (CR;LF). Is there anyway to configure plog to always add \r to the end of a log message, so that each message is on its own line?

Thanks a lot!

**Comment by grandtiger** [comment]
Never mind. I just read on and found another example at: https://github.com/SergiusTheBest/plog/tree/master/samples/NativeEOL

**Comment by SergiusTheBest** [comment]
That's right.
