### ISSUE TITLE
Can it be used for multi-process environments?

### ISSUE THREAD

**Issue by webcpp** [SergiusTheBest/plog#82]
Can it be used for multi-process environments?

**Comment by SergiusTheBest** [comment]
At the moment writing to a file doesn't support multiple processes. But this feature is in the plans.

**Comment by webcpp** [comment]
Thanks.

**Comment by TsArun-ArunTs** [comment]
@SergiusTheBest Is it implemented yet? Been 2 years!

**Comment by SergiusTheBest** [comment]
@TsArun-ArunTs I recommend to use a log file per process. In most cases it has more sense than dumping everything into one file.

About the feature: I don't see a big interest of the community in it. Add comments, likes, send pull-requests - any contribution is welcomed!
