### ISSUE TITLE
intel compiler

### ISSUE THREAD

**Issue by mmedvin** [SergiusTheBest/plog#84]
I have an issue compiling plog with intel compiler.
no such an issue with MSVSC++, but switching to intel even  with simple example end's with 

> error : expected an identifier
> 1>  		LOG_DEBUG<< "something";
> 1>  		^

**Comment by SergiusTheBest** [comment]
It should work now. Please check at your side.

**Comment by mmedvin** [comment]
looks ok so far! thanks!

**Comment by SergiusTheBest** [comment]
good
