### ISSUE TITLE
Several libraries write in one file

### ISSUE THREAD

**Issue by FarafontovDmitriy** [SergiusTheBest/plog#85]
I have several shared libraries. In each I do the following : 
```
class Lib1 
{
public:
	enum Loggers
	{
		DEFAULT,
		DATA
	};
	void initLog(string logFileName)
	{
		if (plog::get<Loggers::DEFAULT>() == nullptr)
			plog::init<Loggers::DEFAULT>(plog::Severity::debug, logFileName.c_str());
	}
};

class Lib2 
{
public:
	enum Loggers
	{
		DEFAULT,
		DATA
	};
	void initLog(string logFileName)
	{
		if (plog::get<Loggers::DEFAULT>() == nullptr)
			plog::init<Loggers::DEFAULT>(plog::Severity::debug, logFileName.c_str());
	}
};
```
After that all the libraries write in one file. It is possible as that to bypass this problem?

**Comment by SergiusTheBest** [comment]
Hi!

If they are shared libraries you can use the following approach: https://github.com/SergiusTheBest/plog/tree/master/samples/Chained

**Comment by FarafontovDmitriy** [comment]
I would like every library to write to your file. With this approach, the file will be one ...

**Comment by SergiusTheBest** [comment]
I think I know what the problem is. You need to hide all symbols by default (`-fvisibility=hidden` on gcc/clang). Or else both libraries will use the same instance of the logger object as it will be public.

**Comment by FarafontovDmitriy** [comment]
Thank! It helped me!

**Comment by SergiusTheBest** [comment]
Perfect! It's a general recommendation to hide all symbols by default: 
> Reducing the number of symbols in your libraries also decreases the footprint of your library and reduces the amount of work that must be done by the dynamic linker. With fewer symbols to load and resolve, the dynamic linker is able to get your program up and running more quickly.
