### ISSUE TITLE
error: expected primary-expression before ‘if’

### ISSUE THREAD

**Issue by rhymerjr** [SergiusTheBest/plog#88]
Hi !

Why I am getting this ?

**./plog/Log.h:36:41: error: expected primary-expression before ‘if’
 #define IF_LOG_(instance, severity)     if (!plog::get<instance>() || !plog::get<instance>()->checkSeverity(severity)) {;} else
                                         ^**
./plog/Log.h:42:41: note: in expansion of macro ‘IF_LOG_’
 #define LOG_(instance, severity)        IF_LOG_(instance, severity) (*plog::get<instance>()) += plog::Record(severity, PLOG_GET_FUNC(), __LINE__, PLOG_GET_FILE(), PLOG_GET_THIS())
                                         ^~~~~~~
./plog/Log.h:43:41: note: in expansion of macro ‘LOG_’
 #define LOG(severity)                   LOG_(PLOG_DEFAULT_INSTANCE, severity)
                                         ^~~~
./plog/Log.h:47:41: note: in expansion of macro ‘LOG’
 #define LOG_INFO                        LOG(plog::info)
                                         ^~~
m_daemon_skeleton_wconf.cpp:236:19: note: in expansion of macro ‘LOG_INFO’
     int LOG_LEVEL=LOG_INFO;

Downloaded version : plog-1.1.3.tar.gz

g++ command:

g++ -m64 -g -std=c++0x -static -static-libstdc++ -I. m_daemon_skeleton_wconf.config.pb.cc m_daemon_skeleton_wconf.cpp -o m_daemon_skeleton_wconf $(pkg-config --libs --cflags protobuf)

**Comment by SergiusTheBest** [comment]
Hi!

This is because LOG_INFO is not `int` but a macro for writing log messages:
```cpp
int LOG_LEVEL=LOG_INFO; // <== wrong
LOG_INFO << "Hello"; // <== correct
```

**Comment by rhymerjr** [comment]
Oh, yes!
Sorry, it was my silly mistake!

Great lib!

Thanks!

**Comment by SergiusTheBest** [comment]
No problem. Have fun!
