### ISSUE TITLE
how can i decrease the application size??

### ISSUE THREAD

**Issue by Leeseokwon** [SergiusTheBest/plog#89]
I use this library because simple to apply but total build app size is increase a lot 
how can i decrease it size well??

**Comment by SergiusTheBest** [comment]
Please, provide more info: what is your compiler, build settings, what size increase do you observe.

**Comment by Leeseokwon** [comment]
my compiler is arm-none-linux-gnueabi-g++  
The previous size was 10mb on my log library, but now it has doubled on plog
I think it's because the headers have increased more than ever.

Do you have any tips to reduce the size even a little? like Separate source file from header..

**Comment by Leeseokwon** [comment]
i resolved it  by remove #include <plog/Init.h> on  plog/Log.h
thanks

**Comment by SergiusTheBest** [comment]
Oh, that's interesting. What size is it now?
