### ISSUE TITLE
multiple loggers - different log levels

### ISSUE THREAD

**Issue by rhd** [SergiusTheBest/plog#9]
Hi,

If I want to log `info` to the console and `debug` to a file I might do something like this:

```
    plog::ConsoleAppender<plog::TxtFormatter> consoleAppender;
    plog::init<0>(plog::info, &consoleAppender);

    static plog::RollingFileAppender<plog::TxtFormatter> fileAppender("MultiAppender.txt", 8000, 3);
    plog::init<1>(plog::debug, &fileAppender);
```
Now hook them up:
```
plog::get<0>()->addAppender(plog::get<1>());
```

The problem is that the debug data never makes it to the 2nd logger because it's filtered by the first one.

Is there a workaround for this? Seems `appenders` are really for logging the same data to multiple sinks.

The only thing that works is if I make sure to have the most verbose logger as logger `<0>` - then data flows to the 2nd logger. 

Thanks for the great library!

**Comment by SergiusTheBest** [comment]
Hi!

You need to use the following configuration:
```cpp
static plog::ConsoleAppender<plog::TxtFormatter> consoleAppender;
plog::init<1>(plog::info, &consoleAppender);

static plog::RollingFileAppender<plog::TxtFormatter> fileAppender("log.txt", 10000000, 3);
plog::init<2>(plog::debug, &fileAppender);

plog::init(plog::debug).addAppender(plog::get<1>()).addAppender(plog::get<2>());
```
All messages go to the default logger first. It performs initial filtering by severity level (in your case it has to be `debug` or higher). Then messages go to the 1st  and 2nd loggers each with its own severity level.

Cheers!

**Comment by rhd** [comment]
Ah. That makes perfect sense. Thanks a lot! You should add this to your many great examples.
