### ISSUE TITLE
CustomType doesn't compile if there is no initial "text"

### ISSUE THREAD

**Issue by agilmor** [SergiusTheBest/plog#94]
The [CustomType sample](https://github.com/SergiusTheBest/plog/blob/master/samples/CustomType/Main.cpp) doesn't compile if we change the line 28 from 

```
    LOGI << "We've got a line with coords: " << pt1 << pt2; // Print our type to the log stream.
```
To 
```
    LOGI << pt1 << pt2; // Print our type to the log stream.
```

It seems that all custom types needs some text before beeing able to be logged?

**Comment by SergiusTheBest** [comment]
Good catch, thanks!

**Comment by SergiusTheBest** [comment]
The issue is resolved.
