### ISSUE TITLE
heap corruption errors occurs when using (INFO, Debug, verbose)

### ISSUE THREAD

**Issue by YannickStephane** [SergiusTheBest/plog#97]
Hi sergius,

I face errors (heap corruption) in my WPF C# app when i try logging in info, debug, verbose. 
It works well when logging in warning, fatal, error.
The logging is done in my VC++ Cli wrapper (dll). Please, can you give a clue why it happens ?
in the dll, LOGD, LOGI, LOGV are used in threads.

Thank you in advance.

**Comment by SergiusTheBest** [comment]
Hi @YannickStephane,

It's hard to tell without the code. Could you prepare a sample project and attach it here?
