### ISSUE TITLE
log for each thread

### ISSUE THREAD

**Issue by jeffrosenthal** [SergiusTheBest/plog#99]
I have been using your logger with success and generally like it.

Is there a way to have one log per thread?  I have many threads in my app and it gets confusing.

**Comment by SergiusTheBest** [comment]
Hi Jeff,

I advice you to try the following approach: use csv format and use LIbreOffice/MsOffice to analyze multithreaded log data. As a rule I add autofilter and conditional formatting for TID so it's easy to filter out threads and visually differentiate them. It looks like this (I have no real csv log right now so I used a sample csv data):
![screenshot from 2018-06-12 08-56-21](https://user-images.githubusercontent.com/4660722/41272672-c1e4e444-6e1e-11e8-9bd3-a9864906d278.png)

If you really need a per thread log you have to write your own component - I think it can be a wrapper around `RollingFileAppender` with a per-thread storage. It's relatively easy can be done with `thread_local` from C++11.
